# Tutoring Business Data Simulation

This project is based on a real tutoring business model.  
All data has been anonymised and partially simulated to reflect realistic operational patterns.

The aim of this dataset is to recreate key elements of a tutoring business, including:
- tutor capacity and availability
- student demand and characteristics
- scheduling constraints

This dataset is designed to support further analysis such as:
- revenue optimisation
- capacity planning
- lesson scheduling

In [54]:
import pandas as pd
import numpy as np
from faker import Faker
from pathlib import Path

fake = Faker("pl_PL")

BASE_DIR = Path.cwd().parent
DATA_RAW = BASE_DIR / "data_raw"

In [55]:
from pathlib import Path

BASE_DIR = Path.cwd().parent
DATA_RAW = BASE_DIR / "data_raw"
DATA_CLEAN = BASE_DIR / "data_clean"

DATA_CLEAN.mkdir(exist_ok=True)

print("DATA_CLEAN path:", DATA_CLEAN)

DATA_CLEAN path: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_clean

## Tutors Dataset

This dataset reflects real tutor profiles observed in a tutoring business.

Tutors differ in:
- experience level
- hourly rates
- availability patterns
- weekly capacity

These differences are important for analysing scheduling efficiency and revenue potential.

In [56]:
tutors = [
    {
        "tutor_id": 1,
        "tutor_name": fake.name(),
        "experience_level": "senior",
        "hourly_rate": 120,
        "max_weekly_hours": 26,
        "preferred_mode": "mixed",
        "home_area": "Warsaw"
    },
    {
        "tutor_id": 2,
        "tutor_name": fake.name(),
        "experience_level": "mid",
        "hourly_rate": 100,
        "max_weekly_hours": 23,
        "preferred_mode": "mixed",
        "home_area": "Warsaw"
    },
    {
        "tutor_id": 3,
        "tutor_name": fake.name(),
        "experience_level": "mid",
        "hourly_rate": 95,
        "max_weekly_hours": 21,
        "preferred_mode": "online",
        "home_area": "Warsaw"
    },
    {
        "tutor_id": 4,
        "tutor_name": fake.name(),
        "experience_level": "senior",
        "hourly_rate": 110,
        "max_weekly_hours": 26,
        "preferred_mode": "in_person",
        "home_area": "Warsaw"
    },
    {
        "tutor_id": 5,
        "tutor_name": fake.name(),
        "experience_level": "junior",
        "hourly_rate": 70,
        "max_weekly_hours": 13,
        "preferred_mode": "online",
        "home_area": "Warsaw"
    }
]

df_tutors = pd.DataFrame(tutors)
df_tutors

,tutor_id,tutor_name,experience_level,hourly_rate,max_weekly_hours,preferred_mode,home_area
0,1,Borys Podleśna,senior,120,26,mixed,Warsaw
1,2,Łukasz Wac,mid,100,23,mixed,Warsaw
2,3,Mikołaj Boduch,mid,95,21,online,Warsaw
3,4,Norbert Durlej,senior,110,26,in_person,Warsaw
4,5,Emil Ofiara,junior,70,13,online,Warsaw

In [57]:
file_path = DATA_RAW / "tutors.csv"

df_tutors.to_csv(file_path, index=False, encoding="utf-8-sig")

print("File saved:", file_path)

File saved: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\tutors.csv

## Students Dataset

This dataset simulates student profiles based on typical tutoring business patterns.

Students vary by:
- age group
- language level (CEFR)
- learning goals
- attendance behaviour

This diversity impacts lesson scheduling and overall business performance.

In [58]:
import random

students = []

age_groups = ["child", "pre_teen", "teen", "exam_prep", "adult"]
cefr_levels = ["A1", "A2", "B1", "B2", "C1"]
learning_goals = ["school", "matura_basic", "matura_extended", "conversation", "general"]
modes = ["online", "in_person"]

for i in range(1, 126):
    student = {
        "student_id": i,
        "student_name": fake.name(),
        "age_group": random.choice(age_groups),
        "cefr_level": random.choice(cefr_levels),
        "learning_goal": random.choice(learning_goals),
        "preferred_mode": random.choice(modes),
        "home_area": "Warsaw",
        "sibling_group_id": None, 
        "start_month": random.choice([9,10,11,12,1,2,3,4,5,6])
    }
    students.append(student)

df_students = pd.DataFrame(students)

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month
0,1,Agnieszka Kawulok,adult,A1,general,in_person,Warsaw,None,2
1,2,Kornelia Karłowicz,adult,B2,matura_basic,online,Warsaw,None,5
2,3,Tymoteusz Dycha,adult,B1,matura_extended,in_person,Warsaw,None,9
3,4,Sandra Daniec,exam_prep,A1,matura_extended,in_person,Warsaw,None,3
4,5,Kornelia Komisarek,pre_teen,C1,school,online,Warsaw,None,5

In [59]:
file_path = DATA_RAW / "students.csv"

df_students.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Saved:", file_path)

Saved: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\students.csv

In [60]:
students = []

for i in range(1, 126):

    age_group = random.choices(
        ["child", "pre_teen", "teen", "exam_prep", "adult"],
        weights=[25, 25, 30, 10, 10]
    )[0]

    # CEFR depends on results
    if age_group == "child":
        cefr = random.choice(["A1", "A2"])
    elif age_group == "pre_teen":
        cefr = random.choice(["A1", "A2", "B1"])
    elif age_group == "teen":
        cefr = random.choice(["A2", "B1"])
    elif age_group == "exam_prep":
        cefr = random.choice(["B1", "B2"])
    else:
        cefr = random.choice(["B1", "B2", "C1"])

    # learning goal logic
    if age_group in ["child", "pre_teen"]:
        goal = "school"
    elif age_group == "exam_prep":
        goal = random.choice(["matura_basic", "matura_extended"])
    elif age_group == "teen":
        goal = random.choice(["school", "matura_basic"])
    else:
        goal = random.choice(["conversation", "general"])

    student = {
        "student_id": i,
        "student_name": fake.name(),
        "age_group": age_group,
        "cefr_level": cefr,
        "learning_goal": goal,
        "preferred_mode": random.choice(["online", "in_person"]),
        "home_area": "Warsaw",
        "sibling_group_id": None,
        "start_month": random.choice([9,10,11,12,1,2,3,4,5,6])
    }

    students.append(student)

df_students = pd.DataFrame(students)

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month
0,1,Anastazja Swiątek,exam_prep,B1,matura_basic,in_person,Warsaw,None,4
1,2,pan Jędrzej Hein,child,A1,school,online,Warsaw,None,5
2,3,Ewelina Chorążewicz,adult,B2,general,in_person,Warsaw,None,5
3,4,Olaf Tymczyszyn,teen,A2,school,online,Warsaw,None,12
4,5,pani Klara Koj,pre_teen,A2,school,in_person,Warsaw,None,3

In [61]:
file_path = DATA_RAW / "students.csv"

df_students.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Updated:", file_path)

Updated: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\students.csv

## 3. Sibling Groups

This section assigns some students to sibling groups.

The purpose is to simulate realistic family-based enrolment patterns, where more than one student may come from the same household.

This matters because sibling groups can influence:
- lesson scheduling
- retention patterns
- household-level pricing decisions

In [62]:
df_students = df_students.copy()

df_students["sibling_group_id"] = pd.NA

num_students = len(df_students)
target_share = 0.20  # around 20% of students have siblings
target_count = int(num_students * target_share)

available_ids = df_students["student_id"].tolist()
random.shuffle(available_ids)

group_id = 1
assigned_count = 0
idx = 0

while assigned_count < target_count and idx < len(available_ids) - 1:
  # most groups have 2 students, occasionally 3
    group_size = random.choices([2, 3], weights=[85, 15])[0]

    group_members = available_ids[idx:idx + group_size]

    if len(group_members) < 2:
        break

    df_students.loc[df_students["student_id"].isin(group_members), "sibling_group_id"] = group_id

    assigned_count += len(group_members)
    idx += group_size
    group_id += 1

df_students.head(10)

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month
0,1,Anastazja Swiątek,exam_prep,B1,matura_basic,in_person,Warsaw,2,4
1,2,pan Jędrzej Hein,child,A1,school,online,Warsaw,<NA>,5
2,3,Ewelina Chorążewicz,adult,B2,general,in_person,Warsaw,10,5
3,4,Olaf Tymczyszyn,teen,A2,school,online,Warsaw,<NA>,12
4,5,pani Klara Koj,pre_teen,A2,school,in_person,Warsaw,11,3
5,6,Mariusz Zys,adult,B2,conversation,in_person,Warsaw,<NA>,4
6,7,Łukasz Pitala,pre_teen,A1,school,in_person,Warsaw,<NA>,12
7,8,pan Fryderyk Olas,pre_teen,A2,school,in_person,Warsaw,<NA>,2
8,9,Aleks Szyba,pre_teen,B1,school,online,Warsaw,<NA>,10
9,10,Gustaw Madejczyk,pre_teen,A1,school,in_person,Warsaw,<NA>,3

In [63]:
df_students["sibling_group_id"].value_counts(dropna=False).head(15)

sibling_group_id
<NA>    98
2        3
10       3
12       3
11       2
9        2
5        2
4        2
7        2
1        2
8        2
6        2
3        2
Name: count, dtype: int64

In [64]:
df_students[df_students["sibling_group_id"].notna()].sort_values("sibling_group_id").head(20)

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month
69,70,pan Kajetan Fabiszak,pre_teen,A2,school,in_person,Warsaw,1,2
42,43,Elżbieta Kidoń,pre_teen,A1,school,in_person,Warsaw,1,10
0,1,Anastazja Swiątek,exam_prep,B1,matura_basic,in_person,Warsaw,2,4
90,91,Cyprian Świerad,teen,B1,matura_basic,online,Warsaw,2,4
45,46,Karina Domżał,teen,A2,matura_basic,online,Warsaw,2,3
111,112,pani Dorota Choroś,child,A2,school,in_person,Warsaw,3,9
122,123,Michał Gruszczyk,teen,A2,matura_basic,online,Warsaw,3,12
103,104,Błażej Betlej,child,A1,school,online,Warsaw,4,4
28,29,Kajetan Włodyka,adult,B2,conversation,in_person,Warsaw,4,1
20,21,Tymoteusz Martyka,exam_prep,B2,matura_basic,online,Warsaw,5,5
117,118,Julita Mikita,child,A1,school,online,Warsaw,5,12
116,117,pan Daniel Henke,teen,B1,matura_basic,in_person,Warsaw,6,6
86,87,pani Sara Wilma,teen,B1,matura_basic,in_person,Warsaw,6,6
31,32,Patryk Majerczyk,pre_teen,A1,school,in_person,Warsaw,7,12
82,83,Maksymilian Hutnik,child,A2,school,in_person,Warsaw,7,6
104,105,Sylwia Misiuk,teen,A2,school,online,Warsaw,8,12
43,44,Urszula Osica,adult,B2,general,online,Warsaw,8,11
65,66,pan Cyprian Goliszek,child,A2,school,in_person,Warsaw,9,9
19,20,Elżbieta Świergiel,adult,B1,conversation,in_person,Warsaw,9,12
17,18,Iwo Hojda,teen,A2,school,in_person,Warsaw,10,10

In [65]:
file_path = DATA_RAW / "students.csv"

df_students.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Updated:", file_path)

Updated: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\students.csv

## 4. Tutor Availability

This section generates tutor availability across weekdays and time blocks.

Availability is modelled to reflect realistic working patterns, taking into account:
- preferred teaching days
- time-of-day preferences
- maximum weekly hours

This creates realistic capacity constraints for later scheduling analysis.

In [66]:
weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
time_blocks = [
    "08:00-09:00",
    "09:00-10:00",
    "10:00-11:00",
    "11:00-12:00",
    "12:00-13:00",
    "13:00-14:00",
    "14:00-15:00",
    "15:00-16:00",
    "16:00-17:00",
    "17:00-18:00",
    "18:00-19:00",
    "19:00-20:00",
    "20:00-21:00"
]

tutor_availability = []
availability_id = 1

In [67]:
for _, tutor in df_tutors.iterrows():
    tutor_id = tutor["tutor_id"]
    preferred_mode = tutor["preferred_mode"]
    max_hours = tutor["max_weekly_hours"]

    for day in weekdays:
        for block in time_blocks:

            start_hour = int(block.split(":")[0])

            # base availability logic
            if tutor_id == 5:
                # student tutor - fewer hours, mainly afternoons and evenings
                available = 1 if day in ["Monday", "Wednesday", "Friday", "Saturday"] and start_hour >= 15 else 0

            elif tutor_id == 3:
                # online tutor - mainly afternoons, no Saturday mornings
                available = 1 if start_hour >= 14 and day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] else 0

            elif tutor_id == 4:
                # in-person tutor - more traditional schedule
                available = 1 if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] and 10 <= start_hour <= 18 else 0

            else:
                # mixed-mode tutors
                available = 1 if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] and 12 <= start_hour <= 20 else 0

            tutor_availability.append({
                "availability_id": availability_id,
                "tutor_id": tutor_id,
                "weekday": day,
                "time_block": block,
                "available_flag": available
            })

            availability_id += 1

df_tutor_availability = pd.DataFrame(tutor_availability)
df_tutor_availability.head(20)

    availability_id  tutor_id  weekday   time_block  available_flag
0                 1         1   Monday  08:00-09:00               0
1                 2         1   Monday  09:00-10:00               0
2                 3         1   Monday  10:00-11:00               0
3                 4         1   Monday  11:00-12:00               0
4                 5         1   Monday  12:00-13:00               1
5                 6         1   Monday  13:00-14:00               1
6                 7         1   Monday  14:00-15:00               1
7                 8         1   Monday  15:00-16:00               1
8                 9         1   Monday  16:00-17:00               1
9                10         1   Monday  17:00-18:00               1
10               11         1   Monday  18:00-19:00               1
11               12         1   Monday  19:00-20:00               1
12               13         1   Monday  20:00-21:00               1
13               14         1  Tuesday  08:00-09:00               0
14               15         1  Tuesday  09:00-10:00               0
15               16         1  Tuesday  10:00-11:00               0
16               17         1  Tuesday  11:00-12:00               0
17               18         1  Tuesday  12:00-13:00               1
18               19         1  Tuesday  13:00-14:00               1
19               20         1  Tuesday  14:00-15:00               1

In [68]:
df_tutor_availability[df_tutor_availability["available_flag"] == 1].groupby("tutor_id").size()

tutor_id
1    54
2    54
3    35
4    54
5    24
dtype: int64

In [69]:
file_path = DATA_RAW / "tutor_availability.csv"

df_tutor_availability.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Saved:", file_path)

Saved: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\tutor_availability.csv

## Student Availability

This section generates student availability based on age group and typical daily routines.

Availability patterns reflect realistic behaviour observed in a tutoring business:
- younger students are mostly available after school
- older students and exam preparation groups prefer later hours
- adults tend to prefer evening slots

This helps simulate real scheduling constraints when matching students with tutors.

In [70]:
student_availability = []
availability_id = 1

In [71]:
for _, student in df_students.iterrows():
    student_id = student["student_id"]
    age_group = student["age_group"]

    for day in weekdays:
        for block in time_blocks:
            start_hour = int(block.split(":")[0])

            # default: not available
            available = 0

            if age_group == "child":
                # children: mostly after school, some Saturday availability
                if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] and 15 <= start_hour <= 18:
                    available = 1 if random.random() < 0.75 else 0
                elif day == "Saturday" and 9 <= start_hour <= 13:
                    available = 1 if random.random() < 0.50 else 0

            elif age_group == "pre_teen":
                # pre-teens: after school plus slightly later hours
                if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] and 15 <= start_hour <= 19:
                    available = 1 if random.random() < 0.70 else 0
                elif day == "Saturday" and 9 <= start_hour <= 14:
                    available = 1 if random.random() < 0.45 else 0

            elif age_group == "teen":
                # teens: afternoons and evenings
                if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] and 16 <= start_hour <= 20:
                    available = 1 if random.random() < 0.68 else 0
                elif day == "Saturday" and 10 <= start_hour <= 15:
                    available = 1 if random.random() < 0.35 else 0

            elif age_group == "exam_prep":
                # exam preparation students: later hours, often also Saturdays
                if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] and 17 <= start_hour <= 20:
                    available = 1 if random.random() < 0.72 else 0
                elif day == "Saturday" and 10 <= start_hour <= 16:
                    available = 1 if random.random() < 0.40 else 0

            elif age_group == "adult":
                # adults: mainly evenings, occasionally mornings or Saturdays
                if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] and 18 <= start_hour <= 20:
                    available = 1 if random.random() < 0.75 else 0
                elif day == "Saturday" and 9 <= start_hour <= 13:
                    available = 1 if random.random() < 0.30 else 0

            student_availability.append({
                "availability_id": availability_id,
                "student_id": student_id,
                "weekday": day,
                "time_block": block,
                "available_flag": available
            })

            availability_id += 1

df_student_availability = pd.DataFrame(student_availability)
df_student_availability.head(20)

    availability_id  student_id  weekday   time_block  available_flag
0                 1           1   Monday  08:00-09:00               0
1                 2           1   Monday  09:00-10:00               0
2                 3           1   Monday  10:00-11:00               0
3                 4           1   Monday  11:00-12:00               0
4                 5           1   Monday  12:00-13:00               0
5                 6           1   Monday  13:00-14:00               0
6                 7           1   Monday  14:00-15:00               0
7                 8           1   Monday  15:00-16:00               0
8                 9           1   Monday  16:00-17:00               0
9                10           1   Monday  17:00-18:00               0
10               11           1   Monday  18:00-19:00               1
11               12           1   Monday  19:00-20:00               1
12               13           1   Monday  20:00-21:00               1
13               14           1  Tuesday  08:00-09:00               0
14               15           1  Tuesday  09:00-10:00               0
15               16           1  Tuesday  10:00-11:00               0
16               17           1  Tuesday  11:00-12:00               0
17               18           1  Tuesday  12:00-13:00               0
18               19           1  Tuesday  13:00-14:00               0
19               20           1  Tuesday  14:00-15:00               0

In [72]:
df_student_availability[df_student_availability["available_flag"] == 1].groupby("student_id").size().describe()

count    125.00000
mean      17.90400
std        3.26621
min       10.00000
25%       16.00000
50%       18.00000
75%       20.00000
max       25.00000
dtype: float64

In [73]:
sample_students = df_students[["student_id", "age_group"]].head(5)
sample_students

   student_id  age_group
0           1  exam_prep
1           2      child
2           3      adult
3           4       teen
4           5   pre_teen

In [74]:
df_student_availability[
    df_student_availability["student_id"].isin(sample_students["student_id"])
].sort_values(["student_id", "weekday", "time_block"]).head(50)

    availability_id  student_id   weekday   time_block  available_flag
52               53           1    Friday  08:00-09:00               0
53               54           1    Friday  09:00-10:00               0
54               55           1    Friday  10:00-11:00               0
55               56           1    Friday  11:00-12:00               0
56               57           1    Friday  12:00-13:00               0
57               58           1    Friday  13:00-14:00               0
58               59           1    Friday  14:00-15:00               0
59               60           1    Friday  15:00-16:00               0
60               61           1    Friday  16:00-17:00               0
61               62           1    Friday  17:00-18:00               0
62               63           1    Friday  18:00-19:00               0
63               64           1    Friday  19:00-20:00               1
64               65           1    Friday  20:00-21:00               1
0                 1           1    Monday  08:00-09:00               0
1                 2           1    Monday  09:00-10:00               0
2                 3           1    Monday  10:00-11:00               0
3                 4           1    Monday  11:00-12:00               0
4                 5           1    Monday  12:00-13:00               0
5                 6           1    Monday  13:00-14:00               0
6                 7           1    Monday  14:00-15:00               0
7                 8           1    Monday  15:00-16:00               0
8                 9           1    Monday  16:00-17:00               0
9                10           1    Monday  17:00-18:00               0
10               11           1    Monday  18:00-19:00               1
11               12           1    Monday  19:00-20:00               1
12               13           1    Monday  20:00-21:00               1
65               66           1  Saturday  08:00-09:00               0
66               67           1  Saturday  09:00-10:00               0
67               68           1  Saturday  10:00-11:00               1
68               69           1  Saturday  11:00-12:00               1
69               70           1  Saturday  12:00-13:00               0
70               71           1  Saturday  13:00-14:00               1
71               72           1  Saturday  14:00-15:00               0
72               73           1  Saturday  15:00-16:00               0
73               74           1  Saturday  16:00-17:00               0
74               75           1  Saturday  17:00-18:00               0
75               76           1  Saturday  18:00-19:00               0
76               77           1  Saturday  19:00-20:00               0
77               78           1  Saturday  20:00-21:00               0
39               40           1  Thursday  08:00-09:00               0
40               41           1  Thursday  09:00-10:00               0
41               42           1  Thursday  10:00-11:00               0
42               43           1  Thursday  11:00-12:00               0
43               44           1  Thursday  12:00-13:00               0
44               45           1  Thursday  13:00-14:00               0
45               46           1  Thursday  14:00-15:00               0
46               47           1  Thursday  15:00-16:00               0
47               48           1  Thursday  16:00-17:00               0
48               49           1  Thursday  17:00-18:00               1
49               50           1  Thursday  18:00-19:00               0

In [75]:
file_path = DATA_RAW / "student_availability.csv"

df_student_availability.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Saved:", file_path)

Saved: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\student_availability.csv

## 6. Calendar and Working Days

This section creates the business calendar used for lesson scheduling.

It includes:
- weekdays and weekends
- public holidays
- working day flags

This makes it possible to model lessons within a realistic academic-year structure.

In [76]:
calendar_dates = pd.date_range(start="2025-09-01", end="2026-06-30", freq="D")

df_calendar = pd.DataFrame({"date": calendar_dates})
df_calendar.head()

        date
0 2025-09-01
1 2025-09-02
2 2025-09-03
3 2025-09-04
4 2025-09-05

In [77]:
df_calendar["year"] = df_calendar["date"].dt.year
df_calendar["month"] = df_calendar["date"].dt.month
df_calendar["month_name"] = df_calendar["date"].dt.month_name()
df_calendar["weekday"] = df_calendar["date"].dt.day_name()
df_calendar["is_weekend"] = df_calendar["weekday"].isin(["Saturday", "Sunday"]).astype(int)

df_calendar.head()

        date  year  month month_name    weekday  is_weekend
0 2025-09-01  2025      9  September     Monday           0
1 2025-09-02  2025      9  September    Tuesday           0
2 2025-09-03  2025      9  September  Wednesday           0
3 2025-09-04  2025      9  September   Thursday           0
4 2025-09-05  2025      9  September     Friday           0

### Public Holidays

This section defines selected public holidays that may affect lesson scheduling.

Holiday names are provided in both Polish and English to reflect the original business context while ensuring clarity for an international audience.

In [80]:
holidays = [
    "2025-11-01",  # Wszystkich Świętych (All Saints' Day)
    "2025-11-11",  # Święto Niepodległości (Independence Day)
    "2025-12-24",  # Wigilia (Christmas Eve)
    "2025-12-25",  # Boże Narodzenie (Christmas Day)
    "2025-12-26",  # Boże Narodzenie (Boxing Day)
    "2026-01-01",  # Nowy Rok (New Year's Day)
    "2026-01-06",  # Trzech Króli (Epiphany)
    "2026-04-05",  # Wielkanoc (Easter Sunday)
    "2026-04-06",  # Poniedziałek Wielkanocny (Easter Monday)
    "2026-05-01",  # Święto Pracy (Labour Day)
    "2026-05-03",  # Konstytucja 3 Maja (Constitution Day)
    "2026-06-04"   # Boże Ciało (Corpus Christi)
]

df_calendar["is_holiday"] = df_calendar["date"].astype(str).isin(holidays).astype(int)

In [81]:
df_calendar["is_working_day"] = ((df_calendar["is_weekend"] == 0) & (df_calendar["is_holiday"] == 0)).astype(int)

# peak months = pazdziernik–maj
df_calendar["is_peak_month"] = df_calendar["month"].isin([10, 11, 12, 1, 2, 3, 4, 5]).astype(int)

df_calendar.head()

,date,year,month,month_name,weekday,is_weekend,is_holiday,is_working_day,is_peak_month
0,2025-09-01,2025,9,September,Monday,0,0,1,0
1,2025-09-02,2025,9,September,Tuesday,0,0,1,0
2,2025-09-03,2025,9,September,Wednesday,0,0,1,0
3,2025-09-04,2025,9,September,Thursday,0,0,1,0
4,2025-09-05,2025,9,September,Friday,0,0,1,0

In [82]:
df_calendar.sample(10).sort_values("date")

,date,year,month,month_name,weekday,is_weekend,is_holiday,is_working_day,is_peak_month
13,2025-09-14,2025,9,September,Sunday,1,0,0,0
30,2025-10-01,2025,10,October,Wednesday,0,0,1,1
103,2025-12-13,2025,12,December,Saturday,1,0,0,1
108,2025-12-18,2025,12,December,Thursday,0,0,1,1
139,2026-01-18,2026,1,January,Sunday,1,0,0,1
174,2026-02-22,2026,2,February,Sunday,1,0,0,1
180,2026-02-28,2026,2,February,Saturday,1,0,0,1
231,2026-04-20,2026,4,April,Monday,0,0,1,1
248,2026-05-07,2026,5,May,Thursday,0,0,1,1
257,2026-05-16,2026,5,May,Saturday,1,0,0,1

In [83]:
df_calendar[df_calendar["is_holiday"] == 1].sort_values("date")

,date,year,month,month_name,weekday,is_weekend,is_holiday,is_working_day,is_peak_month
61,2025-11-01,2025,11,November,Saturday,1,1,0,1
71,2025-11-11,2025,11,November,Tuesday,0,1,0,1
114,2025-12-24,2025,12,December,Wednesday,0,1,0,1
115,2025-12-25,2025,12,December,Thursday,0,1,0,1
116,2025-12-26,2025,12,December,Friday,0,1,0,1
122,2026-01-01,2026,1,January,Thursday,0,1,0,1
127,2026-01-06,2026,1,January,Tuesday,0,1,0,1
216,2026-04-05,2026,4,April,Sunday,1,1,0,1
217,2026-04-06,2026,4,April,Monday,0,1,0,1
242,2026-05-01,2026,5,May,Friday,0,1,0,1
244,2026-05-03,2026,5,May,Sunday,1,1,0,1
276,2026-06-04,2026,6,June,Thursday,0,1,0,0

In [84]:
file_path = DATA_RAW / "calendar.csv"

df_calendar.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Saved:", file_path)

Saved: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\calendar.csv

## 7. Student Learning Patterns

This section enriches the student dataset with lesson-related characteristics such as:
- lessons per week
- lesson duration
- lesson mode
- preparation profile

These variables help simulate more realistic demand patterns and support later operational analysis.

In [85]:
df_students = df_students.copy()

In [86]:
lessons_per_week_list = []

for _, student in df_students.iterrows():
    age_group = student["age_group"]
    learning_goal = student["learning_goal"]

    if age_group == "exam_prep":
        lessons_per_week = random.choices([1, 2], weights=[40, 60])[0]
    elif age_group == "adult":
        lessons_per_week = random.choices([1, 2], weights=[75, 25])[0]
    else:
        lessons_per_week = random.choices([1, 2], weights=[85, 15])[0]

    lessons_per_week_list.append(lessons_per_week)

df_students["lessons_per_week"] = lessons_per_week_list

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week
0,1,Anastazja Swiątek,exam_prep,B1,matura_basic,in_person,Warsaw,2,4,1
1,2,pan Jędrzej Hein,child,A1,school,online,Warsaw,<NA>,5,2
2,3,Ewelina Chorążewicz,adult,B2,general,in_person,Warsaw,10,5,1
3,4,Olaf Tymczyszyn,teen,A2,school,online,Warsaw,<NA>,12,2
4,5,pani Klara Koj,pre_teen,A2,school,in_person,Warsaw,11,3,1

In [87]:
durations = []

for _, student in df_students.iterrows():
    age_group = student["age_group"]
    learning_goal = student["learning_goal"]

    if age_group == "child":
        duration = random.choices([45, 60], weights=[45, 55])[0]

    elif age_group == "pre_teen":
        duration = random.choices([45, 60, 90], weights=[20, 65, 15])[0]

    elif age_group == "teen":
        duration = random.choices([60, 90], weights=[75, 25])[0]

    elif age_group == "exam_prep":
        if learning_goal == "matura_extended":
            duration = random.choices([60, 90, 120], weights=[20, 60, 20])[0]
        else:
            duration = random.choices([60, 90], weights=[55, 45])[0]

    else:  # adult
        duration = random.choices([60, 90], weights=[70, 30])[0]

    durations.append(duration)

df_students["typical_duration_minutes"] = durations

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week,typical_duration_minutes
0,1,Anastazja Swiątek,exam_prep,B1,matura_basic,in_person,Warsaw,2,4,1,90
1,2,pan Jędrzej Hein,child,A1,school,online,Warsaw,<NA>,5,2,45
2,3,Ewelina Chorążewicz,adult,B2,general,in_person,Warsaw,10,5,1,90
3,4,Olaf Tymczyszyn,teen,A2,school,online,Warsaw,<NA>,12,2,60
4,5,pani Klara Koj,pre_teen,A2,school,in_person,Warsaw,11,3,1,60

In [88]:
assigned_modes = []

for _, student in df_students.iterrows():
    preferred_mode = student["preferred_mode"]
    age_group = student["age_group"]

    if preferred_mode == "online":
        assigned_mode = random.choices(["online", "in_person"], weights=[85, 15])[0]
    elif preferred_mode == "in_person":
        assigned_mode = random.choices(["in_person", "online"], weights=[85, 15])[0]
    else:
        assigned_mode = random.choice(["online", "in_person"])

# slight refinement: children are more likely to prefer in-person lessons
    if age_group == "child" and assigned_mode == "online":
        assigned_mode = random.choices(["in_person", "online"], weights=[65, 35])[0]

    assigned_modes.append(assigned_mode)

df_students["assigned_mode"] = assigned_modes

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week,typical_duration_minutes,assigned_mode
0,1,Anastazja Swiątek,exam_prep,B1,matura_basic,in_person,Warsaw,2,4,1,90,in_person
1,2,pan Jędrzej Hein,child,A1,school,online,Warsaw,<NA>,5,2,45,in_person
2,3,Ewelina Chorążewicz,adult,B2,general,in_person,Warsaw,10,5,1,90,online
3,4,Olaf Tymczyszyn,teen,A2,school,online,Warsaw,<NA>,12,2,60,online
4,5,pani Klara Koj,pre_teen,A2,school,in_person,Warsaw,11,3,1,60,in_person

In [89]:
prep_profiles = []

for _, student in df_students.iterrows():
    age_group = student["age_group"]
    learning_goal = student["learning_goal"]

    if learning_goal == "matura_extended":
        prep_profile = random.choice(["medium", "high"])
    elif learning_goal == "matura_basic":
        prep_profile = random.choice(["low", "medium"])
    elif age_group == "child":
        prep_profile = random.choice(["medium", "high"])
    elif age_group == "adult":
        prep_profile = random.choice(["low", "medium"])
    else:
        prep_profile = random.choice(["low", "medium", "high"])

    prep_profiles.append(prep_profile)

df_students["prep_profile"] = prep_profiles

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week,typical_duration_minutes,assigned_mode,prep_profile
0,1,Anastazja Swiątek,exam_prep,B1,matura_basic,in_person,Warsaw,2,4,1,90,in_person,low
1,2,pan Jędrzej Hein,child,A1,school,online,Warsaw,<NA>,5,2,45,in_person,medium
2,3,Ewelina Chorążewicz,adult,B2,general,in_person,Warsaw,10,5,1,90,online,medium
3,4,Olaf Tymczyszyn,teen,A2,school,online,Warsaw,<NA>,12,2,60,online,low
4,5,pani Klara Koj,pre_teen,A2,school,in_person,Warsaw,11,3,1,60,in_person,low

In [90]:
df_students[[
    "student_id",
    "age_group",
    "cefr_level",
    "learning_goal",
    "lessons_per_week",
    "typical_duration_minutes",
    "assigned_mode",
    "prep_profile"
]].head(15)

,student_id,age_group,cefr_level,learning_goal,lessons_per_week,typical_duration_minutes,assigned_mode,prep_profile
0,1,exam_prep,B1,matura_basic,1,90,in_person,low
1,2,child,A1,school,2,45,in_person,medium
2,3,adult,B2,general,1,90,online,medium
3,4,teen,A2,school,2,60,online,low
4,5,pre_teen,A2,school,1,60,in_person,low
5,6,adult,B2,conversation,1,90,in_person,medium
6,7,pre_teen,A1,school,1,45,online,high
7,8,pre_teen,A2,school,1,60,online,high
8,9,pre_teen,B1,school,1,60,online,low
9,10,pre_teen,A1,school,1,60,in_person,high
10,11,child,A1,school,1,60,in_person,high
11,12,teen,A2,school,1,60,in_person,low
12,13,adult,C1,conversation,1,60,online,medium
13,14,teen,A2,school,1,90,in_person,medium
14,15,pre_teen,A1,school,1,60,in_person,high

In [92]:
print("Lessons per week:")
print(df_students["lessons_per_week"].value_counts())
print()

print("Typical duration:")
print(df_students["typical_duration_minutes"].value_counts().sort_index())
print()

print("Assigned mode:")
print(df_students["assigned_mode"].value_counts())
print()

print("Prep profile:")
print(df_students["prep_profile"].value_counts())

Lessons per week:
lessons_per_week
1    93
2    32
Name: count, dtype: int64

Typical duration:
typical_duration_minutes
45    17
60    77
90    31
Name: count, dtype: int64

Assigned mode:
assigned_mode
in_person    72
online       53
Name: count, dtype: int64

Prep profile:
prep_profile
medium    52
low       37
high      36
Name: count, dtype: int64

In [93]:
file_path = DATA_RAW / "students.csv"

df_students.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Updated:", file_path)

Updated: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\students.csv

In [94]:
df_tutors

,tutor_id,tutor_name,experience_level,hourly_rate,max_weekly_hours,preferred_mode,home_area
0,1,Borys Podleśna,senior,120,26,mixed,Warsaw
1,2,Łukasz Wac,mid,100,23,mixed,Warsaw
2,3,Mikołaj Boduch,mid,95,21,online,Warsaw
3,4,Norbert Durlej,senior,110,26,in_person,Warsaw
4,5,Emil Ofiara,junior,70,13,online,Warsaw

## Tutor Assignment

This section assigns tutors to students based on selected business rules.

The matching logic takes into account:
- lesson mode
- student age group
- learning goal
- tutor experience
- tutor availability patterns

This helps simulate more realistic tutor-student matching within the business model.

In [95]:
def choose_tutor(student_row, tutors_df):
    age_group = student_row["age_group"]
    learning_goal = student_row["learning_goal"]
    assigned_mode = student_row["assigned_mode"]

    possible_tutors = tutors_df.copy()

    # 1. lesson mode
    if assigned_mode == "online":
        filtered = possible_tutors[possible_tutors["preferred_mode"].isin(["online", "mixed"])]
    else:
        filtered = possible_tutors[possible_tutors["preferred_mode"].isin(["in_person", "mixed"])]

    if len(filtered) > 0:
        possible_tutors = filtered

    # 2. exam preparation students are more often assigned to more experienced tutors
    if age_group == "exam_prep" or learning_goal in ["matura_basic", "matura_extended"]:
        filtered = possible_tutors[possible_tutors["experience_level"].isin(["mid", "senior"])]
        if len(filtered) > 0:
            possible_tutors = filtered

    # 3. adults are more often assigned to online or mixed-mode tutors
    if age_group == "adult":
        filtered = possible_tutors[possible_tutors["preferred_mode"].isin(["online", "mixed"])]
        if len(filtered) > 0:
            possible_tutors = filtered

    # 4. children are more often assigned to mixed-mode or in-person tutors
    if age_group == "child":
        filtered = possible_tutors[possible_tutors["preferred_mode"].isin(["in_person", "mixed"])]
        if len(filtered) > 0:
            possible_tutors = filtered

    # 5. tutor 5 is assigned fewer students
    tutor_ids = possible_tutors["tutor_id"].tolist()

    weights_map = {
        1: 1.2,
        2: 1.0,
        3: 0.9,
        4: 1.1,
        5: 0.5
    }

    weights = [weights_map[tutor_id] for tutor_id in tutor_ids]

    chosen_tutor_id = random.choices(tutor_ids, weights=weights, k=1)[0]

    return chosen_tutor_id

In [96]:
assigned_tutor_ids = []

for _, student in df_students.iterrows():
    tutor_id = choose_tutor(student, df_tutors)
    assigned_tutor_ids.append(tutor_id)

df_students["assigned_tutor_id"] = assigned_tutor_ids
df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week,typical_duration_minutes,assigned_mode,prep_profile,assigned_tutor_id
0,1,Anastazja Swiątek,exam_prep,B1,matura_basic,in_person,Warsaw,2,4,1,90,in_person,low,2
1,2,pan Jędrzej Hein,child,A1,school,online,Warsaw,<NA>,5,2,45,in_person,medium,2
2,3,Ewelina Chorążewicz,adult,B2,general,in_person,Warsaw,10,5,1,90,online,medium,5
3,4,Olaf Tymczyszyn,teen,A2,school,online,Warsaw,<NA>,12,2,60,online,low,5
4,5,pani Klara Koj,pre_teen,A2,school,in_person,Warsaw,11,3,1,60,in_person,low,2

In [97]:
tutor_name_map = dict(zip(df_tutors["tutor_id"], df_tutors["tutor_name"]))

df_students["assigned_tutor_name"] = df_students["assigned_tutor_id"].map(tutor_name_map)

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week,typical_duration_minutes,assigned_mode,prep_profile,assigned_tutor_id,assigned_tutor_name
0,1,Anastazja Swiątek,exam_prep,B1,matura_basic,in_person,Warsaw,2,4,1,90,in_person,low,2,Łukasz Wac
1,2,pan Jędrzej Hein,child,A1,school,online,Warsaw,<NA>,5,2,45,in_person,medium,2,Łukasz Wac
2,3,Ewelina Chorążewicz,adult,B2,general,in_person,Warsaw,10,5,1,90,online,medium,5,Emil Ofiara
3,4,Olaf Tymczyszyn,teen,A2,school,online,Warsaw,<NA>,12,2,60,online,low,5,Emil Ofiara
4,5,pani Klara Koj,pre_teen,A2,school,in_person,Warsaw,11,3,1,60,in_person,low,2,Łukasz Wac

In [98]:
df_students["assigned_tutor_id"].value_counts().sort_index()

assigned_tutor_id
1    43
2    40
3     9
4    24
5     9
Name: count, dtype: int64

In [99]:
df_students.groupby(["assigned_tutor_id", "age_group"]).size().unstack(fill_value=0)

age_group          adult  child  exam_prep  pre_teen  teen
assigned_tutor_id
1                      4     14          5         9    11
2                      4      7          2        15    12
3                      3      0          2         3     1
4                      0     12          3         5     4
5                      3      0          0         2     4

In [100]:
file_path = DATA_RAW / "students.csv"

df_students.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Updated:", file_path)

Updated: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\students.csv

In [101]:
df_tutor_available = df_tutor_availability[df_tutor_availability["available_flag"] == 1].copy()
df_student_available = df_student_availability[df_student_availability["available_flag"] == 1].copy()

In [102]:
df_tutor_available["slot_key"] = df_tutor_available["weekday"] + "|" + df_tutor_available["time_block"]
df_student_available["slot_key"] = df_student_available["weekday"] + "|" + df_student_available["time_block"]

## 9. Weekly Slot Assignment

This section assigns weekly lesson slots by matching tutor and student availability.

The aim is to simulate realistic scheduling constraints and identify how well demand can be matched with available teaching capacity.

In [103]:
def assign_weekly_slots(student_row, df_student_available, df_tutor_available):
    student_id = student_row["student_id"]
    tutor_id = student_row["assigned_tutor_id"]
    lessons_per_week = student_row["lessons_per_week"]

    student_slots = set(
        df_student_available[df_student_available["student_id"] == student_id]["slot_key"]
    )

    tutor_slots = set(
        df_tutor_available[df_tutor_available["tutor_id"] == tutor_id]["slot_key"]
    )

    common_slots = list(student_slots.intersection(tutor_slots))

    if len(common_slots) == 0:
        return []

    # sorting
    weekday_order = {
        "Monday": 1,
        "Tuesday": 2,
        "Wednesday": 3,
        "Thursday": 4,
        "Friday": 5,
        "Saturday": 6
    }

    common_slots_sorted = sorted(
        common_slots,
        key=lambda x: (
            weekday_order[x.split("|")[0]],
            x.split("|")[1]
        )
    )

    # random selection – assign as many slots as required
    if len(common_slots_sorted) <= lessons_per_week:
        selected_slots = common_slots_sorted
    else:
        selected_slots = random.sample(common_slots_sorted, lessons_per_week)

    return selected_slots

In [104]:
weekly_slots = []

for _, student in df_students.iterrows():
    selected_slots = assign_weekly_slots(student, df_student_available, df_tutor_available)

    for slot in selected_slots:
        weekday, time_block = slot.split("|")

        weekly_slots.append({
            "student_id": student["student_id"],
            "assigned_tutor_id": student["assigned_tutor_id"],
            "weekday": weekday,
            "time_block": time_block,
            "assigned_mode": student["assigned_mode"],
            "typical_duration_minutes": student["typical_duration_minutes"],
            "lessons_per_week": student["lessons_per_week"]
        })

df_weekly_slots = pd.DataFrame(weekly_slots)
df_weekly_slots.head(20)

,student_id,assigned_tutor_id,weekday,time_block,assigned_mode,typical_duration_minutes,lessons_per_week
0,1,2,Thursday,17:00-18:00,in_person,90,1
1,2,2,Tuesday,15:00-16:00,in_person,45,2
2,2,2,Wednesday,15:00-16:00,in_person,45,2
3,3,5,Wednesday,18:00-19:00,online,90,1
4,4,5,Monday,20:00-21:00,online,60,2
5,4,5,Wednesday,20:00-21:00,online,60,2
6,5,2,Monday,17:00-18:00,in_person,60,1
7,6,1,Monday,19:00-20:00,in_person,90,1
8,7,2,Thursday,16:00-17:00,online,45,1
9,8,2,Monday,18:00-19:00,online,60,1
10,9,1,Tuesday,18:00-19:00,online,60,1
11,10,2,Monday,17:00-18:00,in_person,60,1
12,11,1,Thursday,17:00-18:00,in_person,60,1
13,12,2,Friday,20:00-21:00,in_person,60,1
14,13,5,Friday,19:00-20:00,online,60,1
15,14,2,Wednesday,16:00-17:00,in_person,90,1
16,15,2,Monday,15:00-16:00,in_person,60,1
17,16,2,Wednesday,19:00-20:00,in_person,60,1
18,17,1,Thursday,18:00-19:00,in_person,60,1
19,18,4,Wednesday,18:00-19:00,in_person,60,1

In [105]:
assigned_counts = df_weekly_slots.groupby("student_id").size().reset_index(name="assigned_slots")

df_check = df_students[["student_id", "lessons_per_week"]].merge(
    assigned_counts,
    on="student_id",
    how="left"
)

df_check["assigned_slots"] = df_check["assigned_slots"].fillna(0).astype(int)

df_check.head(20)

    student_id  lessons_per_week  assigned_slots
0            1                 1               1
1            2                 2               2
2            3                 1               1
3            4                 2               2
4            5                 1               1
5            6                 1               1
6            7                 1               1
7            8                 1               1
8            9                 1               1
9           10                 1               1
10          11                 1               1
11          12                 1               1
12          13                 1               1
13          14                 1               1
14          15                 1               1
15          16                 1               1
16          17                 1               1
17          18                 1               1
18          19                 2               2
19          20                 2               2

In [106]:
df_check[df_check["assigned_slots"] < df_check["lessons_per_week"]]

Empty DataFrame
Columns: [student_id, lessons_per_week, assigned_slots]
Index: []

In [107]:
df_weekly_slots.sort_values(["assigned_tutor_id", "weekday", "time_block"]).head(50)

,student_id,assigned_tutor_id,weekday,time_block,assigned_mode,typical_duration_minutes,lessons_per_week
143,116,1,Friday,16:00-17:00,online,60,1
60,48,1,Friday,17:00-18:00,online,60,1
118,96,1,Friday,17:00-18:00,online,60,1
144,117,1,Friday,18:00-19:00,in_person,60,1
49,40,1,Friday,19:00-20:00,in_person,90,2
57,45,1,Friday,19:00-20:00,in_person,90,2
96,76,1,Friday,19:00-20:00,online,60,1
61,49,1,Friday,20:00-21:00,online,90,2
21,19,1,Monday,15:00-16:00,in_person,60,2
69,55,1,Monday,15:00-16:00,online,60,1
125,103,1,Monday,15:00-16:00,online,45,2
77,62,1,Monday,16:00-17:00,in_person,45,2
99,78,1,Monday,16:00-17:00,online,60,1
45,38,1,Monday,17:00-18:00,in_person,45,2
48,40,1,Monday,18:00-19:00,in_person,90,2
68,54,1,Monday,18:00-19:00,online,60,1
72,57,1,Monday,18:00-19:00,online,60,1
126,103,1,Monday,18:00-19:00,online,45,2
140,114,1,Monday,18:00-19:00,in_person,60,1
7,6,1,Monday,19:00-20:00,in_person,90,1
34,29,1,Monday,19:00-20:00,in_person,60,2
56,45,1,Monday,19:00-20:00,in_person,90,2
133,108,1,Monday,19:00-20:00,online,60,1
33,29,1,Monday,20:00-21:00,in_person,60,2
29,25,1,Saturday,12:00-13:00,online,60,1
78,62,1,Saturday,12:00-13:00,in_person,45,2
26,23,1,Thursday,15:00-16:00,in_person,60,1
30,26,1,Thursday,16:00-17:00,online,60,1
64,51,1,Thursday,16:00-17:00,in_person,90,1
12,11,1,Thursday,17:00-18:00,in_person,60,1
31,27,1,Thursday,17:00-18:00,in_person,60,1
46,39,1,Thursday,17:00-18:00,online,90,2
117,95,1,Thursday,17:00-18:00,in_person,90,1
18,17,1,Thursday,18:00-19:00,in_person,60,1
107,86,1,Thursday,18:00-19:00,online,60,1
109,88,1,Thursday,18:00-19:00,in_person,45,1
120,98,1,Thursday,18:00-19:00,in_person,90,1
91,73,1,Thursday,19:00-20:00,in_person,90,1
47,39,1,Thursday,20:00-21:00,online,90,2
35,30,1,Tuesday,17:00-18:00,in_person,60,1
121,99,1,Tuesday,17:00-18:00,in_person,60,1
10,9,1,Tuesday,18:00-19:00,online,60,1
67,53,1,Tuesday,18:00-19:00,in_person,60,1
73,58,1,Tuesday,19:00-20:00,in_person,60,1
62,49,1,Tuesday,20:00-21:00,online,90,2
106,85,1,Tuesday,20:00-21:00,in_person,60,1
104,83,1,Wednesday,16:00-17:00,online,60,1
44,38,1,Wednesday,17:00-18:00,in_person,45,2
59,47,1,Wednesday,17:00-18:00,online,60,1
110,89,1,Wednesday,17:00-18:00,online,90,1

In [108]:
file_path = DATA_RAW / "weekly_slots.csv"

df_weekly_slots.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Saved:", file_path)

Saved: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\weekly_slots.csv

In [109]:
df_calendar_working = df_calendar[
    (df_calendar["weekday"].isin(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"])) &
    (df_calendar["is_holiday"] == 0)
].copy()

df_calendar_working.head()

,date,year,month,month_name,weekday,is_weekend,is_holiday,is_working_day,is_peak_month
0,2025-09-01,2025,9,September,Monday,0,0,1,0
1,2025-09-02,2025,9,September,Tuesday,0,0,1,0
2,2025-09-03,2025,9,September,Wednesday,0,0,1,0
3,2025-09-04,2025,9,September,Thursday,0,0,1,0
4,2025-09-05,2025,9,September,Friday,0,0,1,0

## 10. Lesson Generation

This section creates the lesson-level dataset.

Each lesson record represents a scheduled teaching event and includes operational, pricing, and delivery-related variables.

This dataset becomes the core fact table for later business analysis.

In [110]:
lesson_rows = []

for _, slot in df_weekly_slots.iterrows():
    student_id = slot["student_id"]
    tutor_id = slot["assigned_tutor_id"]
    weekday = slot["weekday"]
    time_block = slot["time_block"]
    assigned_mode = slot["assigned_mode"]
    duration = slot["typical_duration_minutes"]

    matching_dates = df_calendar_working[df_calendar_working["weekday"] == weekday]

    for _, cal_row in matching_dates.iterrows():
        lesson_rows.append({
            "lesson_date": cal_row["date"],
            "year": cal_row["year"],
            "month": cal_row["month"],
            "month_name": cal_row["month_name"],
            "weekday": weekday,
            "time_block": time_block,
            "student_id": student_id,
            "tutor_id": tutor_id,
            "mode": assigned_mode,
            "duration_minutes": duration
        })

df_lessons = pd.DataFrame(lesson_rows)
df_lessons.head()

,lesson_date,year,month,month_name,weekday,time_block,student_id,tutor_id,mode,duration_minutes
0,2025-09-04,2025,9,September,Thursday,17:00-18:00,1,2,in_person,90
1,2025-09-11,2025,9,September,Thursday,17:00-18:00,1,2,in_person,90
2,2025-09-18,2025,9,September,Thursday,17:00-18:00,1,2,in_person,90
3,2025-09-25,2025,9,September,Thursday,17:00-18:00,1,2,in_person,90
4,2025-10-02,2025,10,October,Thursday,17:00-18:00,1,2,in_person,90

In [111]:
df_lessons = df_lessons.sort_values(["lesson_date", "time_block", "tutor_id", "student_id"]).reset_index(drop=True)
df_lessons["lesson_id"] = range(1, len(df_lessons) + 1)

df_lessons.head()

,lesson_date,year,month,month_name,weekday,time_block,student_id,tutor_id,mode,duration_minutes,lesson_id
0,2025-09-01,2025,9,September,Monday,15:00-16:00,19,1,in_person,60,1
1,2025-09-01,2025,9,September,Monday,15:00-16:00,55,1,online,60,2
2,2025-09-01,2025,9,September,Monday,15:00-16:00,103,1,online,45,3
3,2025-09-01,2025,9,September,Monday,15:00-16:00,15,2,in_person,60,4
4,2025-09-01,2025,9,September,Monday,15:00-16:00,32,2,in_person,60,5

In [112]:
student_columns = [
    "student_id",
    "student_name",
    "age_group",
    "cefr_level",
    "learning_goal",
    "assigned_tutor_id",
    "assigned_tutor_name",
    "prep_profile",
    "sibling_group_id"
]

df_lessons = df_lessons.merge(
    df_students[student_columns],
    on="student_id",
    how="left"
)

df_lessons.head()

,lesson_date,year,month,month_name,weekday,time_block,student_id,tutor_id,mode,duration_minutes,lesson_id,student_name,age_group,cefr_level,learning_goal,assigned_tutor_id,assigned_tutor_name,prep_profile,sibling_group_id
0,2025-09-01,2025,9,September,Monday,15:00-16:00,19,1,in_person,60,1,Julian Raczkiewicz,pre_teen,A1,school,1,Borys Podleśna,low,<NA>
1,2025-09-01,2025,9,September,Monday,15:00-16:00,55,1,online,60,2,Ryszard Wasiewicz,pre_teen,A2,school,1,Borys Podleśna,low,<NA>
2,2025-09-01,2025,9,September,Monday,15:00-16:00,103,1,online,45,3,pani Apolonia Przewoźniak,child,A2,school,1,Borys Podleśna,high,<NA>
3,2025-09-01,2025,9,September,Monday,15:00-16:00,15,2,in_person,60,4,Kacper Tlałka,pre_teen,A1,school,2,Łukasz Wac,high,<NA>
4,2025-09-01,2025,9,September,Monday,15:00-16:00,32,2,in_person,60,5,Patryk Majerczyk,pre_teen,A1,school,2,Łukasz Wac,low,7

In [113]:
tutor_columns = [
    "tutor_id",
    "tutor_name",
    "experience_level",
    "hourly_rate",
    "preferred_mode",
    "home_area"
]

df_lessons = df_lessons.merge(
    df_tutors[tutor_columns],
    on="tutor_id",
    how="left"
)

df_lessons.head()

,lesson_date,year,month,month_name,weekday,time_block,student_id,tutor_id,mode,duration_minutes,...,learning_goal,assigned_tutor_id,assigned_tutor_name,prep_profile,sibling_group_id,tutor_name,experience_level,hourly_rate,preferred_mode,home_area
0,2025-09-01,2025,9,September,Monday,15:00-16:00,19,1,in_person,60,...,school,1,Borys Podleśna,low,<NA>,Borys Podleśna,senior,120,mixed,Warsaw
1,2025-09-01,2025,9,September,Monday,15:00-16:00,55,1,online,60,...,school,1,Borys Podleśna,low,<NA>,Borys Podleśna,senior,120,mixed,Warsaw
2,2025-09-01,2025,9,September,Monday,15:00-16:00,103,1,online,45,...,school,1,Borys Podleśna,high,<NA>,Borys Podleśna,senior,120,mixed,Warsaw
3,2025-09-01,2025,9,September,Monday,15:00-16:00,15,2,in_person,60,...,school,2,Łukasz Wac,high,<NA>,Łukasz Wac,mid,100,mixed,Warsaw
4,2025-09-01,2025,9,September,Monday,15:00-16:00,32,2,in_person,60,...,school,2,Łukasz Wac,low,7,Łukasz Wac,mid,100,mixed,Warsaw

In [114]:
statuses = []

for _, row in df_lessons.iterrows():
    month = row["month"]

    # higher cancellation risk during winter months
    if month in [12, 1, 2]:
        status = random.choices(
            ["completed", "cancelled_by_student", "cancelled_by_tutor", "no_show"],
            weights=[84, 10, 2, 4]
        )[0]
    else:
        status = random.choices(
            ["completed", "cancelled_by_student", "cancelled_by_tutor", "no_show"],
            weights=[88, 7, 2, 3]
        )[0]

    statuses.append(status)

df_lessons["status"] = statuses

df_lessons["status"].value_counts()

status
completed               5739
cancelled_by_student     462
no_show                  217
cancelled_by_tutor       132
Name: count, dtype: int64

In [115]:
prep_times = []

for _, row in df_lessons.iterrows():
    prep_profile = row["prep_profile"]

    if prep_profile == "low":
        prep_time = random.choice([5, 10])
    elif prep_profile == "medium":
        prep_time = random.choice([10, 15])
    else:
        prep_time = random.choice([15, 20])

    prep_times.append(prep_time)

df_lessons["prep_time_minutes"] = prep_times

df_lessons["prep_time_minutes"].value_counts().sort_index()

prep_time_minutes
5      993
10    2373
15    2320
20     864
Name: count, dtype: int64

In [116]:
travel_times = []

for _, row in df_lessons.iterrows():
    if row["mode"] == "in_person":
        travel_time = random.choice([10, 15, 20, 25, 30, 35, 40])
    else:
        travel_time = 0

    travel_times.append(travel_time)

df_lessons["travel_time_minutes"] = travel_times

df_lessons["travel_time_minutes"].value_counts().sort_index()

travel_time_minutes
0     2884
10     560
15     534
20     513
25     544
30     494
35     494
40     527
Name: count, dtype: int64

In [117]:
platforms = []

for _, row in df_lessons.iterrows():
    if row["mode"] == "online":
        platform = random.choices(["Teams", "Skype", "Zoom"], weights=[50, 35, 15])[0]
    else:
        platform = "in_person"

    platforms.append(platform)

df_lessons["platform"] = platforms

df_lessons["platform"].value_counts()

platform
in_person    3666
Teams        1481
Skype         997
Zoom          406
Name: count, dtype: int64

In [118]:
df_lessons["base_price"] = (df_lessons["hourly_rate"] * df_lessons["duration_minutes"] / 60).round(2)

df_lessons[["hourly_rate", "duration_minutes", "base_price"]].head()

   hourly_rate  duration_minutes  base_price
0          120                60       120.0
1          120                60       120.0
2          120                45        90.0
3          100                60       100.0
4          100                60       100.0

In [119]:
discount_types = []
final_prices = []

for _, row in df_lessons.iterrows():
    base_price = row["base_price"]
    sibling_group_id = row["sibling_group_id"]
    duration = row["duration_minutes"]

    discount_type = "none"
    discount = 0.0

    if pd.notna(sibling_group_id):
        discount_type = "sibling_discount"
        discount = 0.10

    if duration >= 90:
        if discount_type == "none":
            discount_type = "long_lesson_discount"
            discount = 0.08
        else:
            discount_type = "sibling_and_long_lesson"
            discount = 0.15

    final_price = round(base_price * (1 - discount), 2)

    discount_types.append(discount_type)
    final_prices.append(final_price)

df_lessons["discount_type"] = discount_types
df_lessons["final_price"] = final_prices

df_lessons[["base_price", "discount_type", "final_price"]].head(10)

   base_price         discount_type  final_price
0      120.00                  none       120.00
1      120.00                  none       120.00
2       90.00                  none        90.00
3      100.00                  none       100.00
4      100.00      sibling_discount        90.00
5      150.00  long_lesson_discount       138.00
6       90.00                  none        90.00
7      120.00      sibling_discount       108.00
8      150.00  long_lesson_discount       138.00
9       71.25                  none        71.25

In [120]:
df_lessons.head(20)

,lesson_date,year,month,month_name,weekday,time_block,student_id,tutor_id,mode,duration_minutes,...,hourly_rate,preferred_mode,home_area,status,prep_time_minutes,travel_time_minutes,platform,base_price,discount_type,final_price
0,2025-09-01,2025,9,September,Monday,15:00-16:00,19,1,in_person,60,...,120,mixed,Warsaw,completed,5,25,in_person,120.00,none,120.00
1,2025-09-01,2025,9,September,Monday,15:00-16:00,55,1,online,60,...,120,mixed,Warsaw,completed,10,0,Skype,120.00,none,120.00
2,2025-09-01,2025,9,September,Monday,15:00-16:00,103,1,online,45,...,120,mixed,Warsaw,completed,20,0,Teams,90.00,none,90.00
3,2025-09-01,2025,9,September,Monday,15:00-16:00,15,2,in_person,60,...,100,mixed,Warsaw,completed,15,20,in_person,100.00,none,100.00
4,2025-09-01,2025,9,September,Monday,15:00-16:00,32,2,in_person,60,...,100,mixed,Warsaw,completed,10,20,in_person,100.00,sibling_discount,90.00
5,2025-09-01,2025,9,September,Monday,15:00-16:00,64,2,in_person,90,...,100,mixed,Warsaw,completed,15,40,in_person,150.00,long_lesson_discount,138.00
6,2025-09-01,2025,9,September,Monday,16:00-17:00,62,1,in_person,45,...,120,mixed,Warsaw,completed,15,10,in_person,90.00,none,90.00
7,2025-09-01,2025,9,September,Monday,16:00-17:00,78,1,online,60,...,120,mixed,Warsaw,completed,10,0,Zoom,120.00,sibling_discount,108.00
8,2025-09-01,2025,9,September,Monday,16:00-17:00,107,2,online,90,...,100,mixed,Warsaw,completed,10,0,Teams,150.00,long_lesson_discount,138.00
9,2025-09-01,2025,9,September,Monday,16:00-17:00,79,3,online,45,...,95,online,Warsaw,completed,15,0,Teams,71.25,none,71.25
10,2025-09-01,2025,9,September,Monday,16:00-17:00,111,5,online,90,...,70,online,Warsaw,completed,20,0,Teams,105.00,long_lesson_discount,96.60
11,2025-09-01,2025,9,September,Monday,17:00-18:00,38,1,in_person,45,...,120,mixed,Warsaw,no_show,15,15,in_person,90.00,none,90.00
12,2025-09-01,2025,9,September,Monday,17:00-18:00,5,2,in_person,60,...,100,mixed,Warsaw,completed,5,10,in_person,100.00,sibling_discount,90.00
13,2025-09-01,2025,9,September,Monday,17:00-18:00,10,2,in_person,60,...,100,mixed,Warsaw,completed,20,10,in_person,100.00,none,100.00
14,2025-09-01,2025,9,September,Monday,17:00-18:00,67,2,in_person,60,...,100,mixed,Warsaw,completed,10,40,in_person,100.00,none,100.00
15,2025-09-01,2025,9,September,Monday,17:00-18:00,109,3,online,60,...,95,online,Warsaw,no_show,15,0,Zoom,95.00,none,95.00
16,2025-09-01,2025,9,September,Monday,17:00-18:00,56,4,in_person,90,...,110,in_person,Warsaw,completed,20,20,in_person,165.00,long_lesson_discount,151.80
17,2025-09-01,2025,9,September,Monday,18:00-19:00,40,1,in_person,90,...,120,mixed,Warsaw,completed,5,10,in_person,180.00,long_lesson_discount,165.60
18,2025-09-01,2025,9,September,Monday,18:00-19:00,54,1,online,60,...,120,mixed,Warsaw,completed,5,0,Teams,120.00,none,120.00
19,2025-09-01,2025,9,September,Monday,18:00-19:00,57,1,online,60,...,120,mixed,Warsaw,completed,10,0,Zoom,120.00,none,120.00

In [121]:
df_lessons.shape

(6550, 31)

In [122]:
file_path = DATA_RAW / "lessons.csv"

df_lessons.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Saved:", file_path)

Saved: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\lessons.csv

## 11. Payments Dataset

This section creates the payments dataset linked to lessons.

It simulates realistic payment outcomes such as:
- paid
- pending
- overdue
- cancelled-related non-payment

This supports analysis of revenue flow and payment behaviour.

In [123]:
payment_rows = []

In [124]:
for _, row in df_lessons.iterrows():
    lesson_id = row["lesson_id"]
    lesson_date = row["lesson_date"]
    status = row["status"]
    amount_due = row["final_price"]

    if status == "completed":
        payment_status = random.choices(
            ["paid", "late", "missing"],
            weights=[88, 9, 3]
        )[0]

        if payment_status == "paid":
            amount_paid = amount_due
        elif payment_status == "late":
            amount_paid = amount_due
        else:
            amount_paid = 0

    elif status == "cancelled_by_student":
        payment_status = random.choices(
            ["paid", "partial", "missing"],
            weights=[20, 35, 45]
        )[0]

        if payment_status == "paid":
            amount_paid = amount_due
        elif payment_status == "partial":
            amount_paid = round(amount_due * 0.5, 2)
        else:
            amount_paid = 0

    elif status == "cancelled_by_tutor":
        payment_status = "waived"
        amount_paid = 0

    else:  # no_show
        payment_status = random.choices(
            ["paid", "partial", "missing"],
            weights=[45, 25, 30]
        )[0]

        if payment_status == "paid":
            amount_paid = amount_due
        elif payment_status == "partial":
            amount_paid = round(amount_due * 0.5, 2)
        else:
            amount_paid = 0

    payment_rows.append({
        "lesson_id": lesson_id,
        "lesson_date": lesson_date,
        "amount_due": amount_due,
        "amount_paid": amount_paid,
        "payment_status": payment_status
    })

df_payments = pd.DataFrame(payment_rows)
df_payments.head()

   lesson_id lesson_date  amount_due  amount_paid payment_status
0          1  2025-09-01       120.0        120.0           paid
1          2  2025-09-01       120.0        120.0           paid
2          3  2025-09-01        90.0         90.0           paid
3          4  2025-09-01       100.0        100.0           late
4          5  2025-09-01        90.0          0.0        missing

In [125]:
df_payments["payment_id"] = range(1, len(df_payments) + 1)
df_payments.head()

   lesson_id lesson_date  amount_due  amount_paid payment_status  payment_id
0          1  2025-09-01       120.0        120.0           paid           1
1          2  2025-09-01       120.0        120.0           paid           2
2          3  2025-09-01        90.0         90.0           paid           3
3          4  2025-09-01       100.0        100.0           late           4
4          5  2025-09-01        90.0          0.0        missing           5

In [126]:
payment_dates = []

for _, row in df_payments.iterrows():
    lesson_date = pd.to_datetime(row["lesson_date"])
    payment_status = row["payment_status"]

    if payment_status == "paid":
        offset_days = random.choice([0, 1, 2, 3])
        payment_date = lesson_date + pd.Timedelta(days=offset_days)

    elif payment_status == "late":
        offset_days = random.choice([5, 7, 10, 14])
        payment_date = lesson_date + pd.Timedelta(days=offset_days)

    elif payment_status == "partial":
        offset_days = random.choice([0, 2, 5, 7])
        payment_date = lesson_date + pd.Timedelta(days=offset_days)

    else:
        payment_date = pd.NaT

    payment_dates.append(payment_date)

df_payments["payment_date"] = payment_dates
df_payments.head()

,lesson_id,lesson_date,amount_due,amount_paid,payment_status,payment_id,payment_date
0,1,2025-09-01,120.0,120.0,paid,1,2025-09-04
1,2,2025-09-01,120.0,120.0,paid,2,2025-09-01
2,3,2025-09-01,90.0,90.0,paid,3,2025-09-01
3,4,2025-09-01,100.0,100.0,late,4,2025-09-06
4,5,2025-09-01,90.0,0.0,missing,5,NaT

In [127]:
df_payments = df_payments[
    [
        "payment_id",
        "lesson_id",
        "lesson_date",
        "amount_due",
        "amount_paid",
        "payment_status",
        "payment_date"
    ]
]

df_payments.head()

,payment_id,lesson_id,lesson_date,amount_due,amount_paid,payment_status,payment_date
0,1,1,2025-09-01,120.0,120.0,paid,2025-09-04
1,2,2,2025-09-01,120.0,120.0,paid,2025-09-01
2,3,3,2025-09-01,90.0,90.0,paid,2025-09-01
3,4,4,2025-09-01,100.0,100.0,late,2025-09-06
4,5,5,2025-09-01,90.0,0.0,missing,NaT

In [128]:
print(df_payments["payment_status"].value_counts())
print()
print(df_payments[["amount_due", "amount_paid"]].describe())

payment_status
paid       5162
late        555
missing     479
partial     222
waived      132
Name: count, dtype: int64

        amount_due  amount_paid
count  6550.000000  6550.000000
mean    110.273122    98.093385
std      26.473314    41.265003
min      70.000000     0.000000
25%      90.000000    85.500000
50%     100.000000   100.000000
75%     120.000000   120.000000
max     165.600000   165.600000

In [129]:
file_path = DATA_RAW / "payments.csv"

df_payments.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Saved:", file_path)

Saved: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\payments.csv

## 12. Data Quality Checks

This section performs final validation checks across the generated datasets.

The goal is to confirm that the data is internally consistent and ready for analysis.

In [130]:
print("tutors:", df_tutors.shape)
print("students:", df_students.shape)
print("tutor_availability:", df_tutor_availability.shape)
print("student_availability:", df_student_availability.shape)
print("calendar:", df_calendar.shape)
print("weekly_slots:", df_weekly_slots.shape)
print("lessons:", df_lessons.shape)
print("payments:", df_payments.shape)

tutors: (5, 7)
students: (125, 15)
tutor_availability: (390, 5)
student_availability: (9750, 5)
calendar: (303, 9)
weekly_slots: (157, 7)
lessons: (6550, 31)
payments: (6550, 7)

In [131]:
def missing_summary(df, df_name):
    missing = df.isna().sum()
    missing = missing[missing > 0]

    print(f"\nMissing values in {df_name}:")
    if len(missing) == 0:
        print("No missing values")
    else:
        print(missing.sort_values(ascending=False))

missing_summary(df_tutors, "df_tutors")
missing_summary(df_students, "df_students")
missing_summary(df_tutor_availability, "df_tutor_availability")
missing_summary(df_student_availability, "df_student_availability")
missing_summary(df_calendar, "df_calendar")
missing_summary(df_weekly_slots, "df_weekly_slots")
missing_summary(df_lessons, "df_lessons")
missing_summary(df_payments, "df_payments")

Missing values in df_tutors:
No missing values

Missing values in df_students:
sibling_group_id    98
dtype: int64

Missing values in df_tutor_availability:
No missing values

Missing values in df_student_availability:
No missing values

Missing values in df_calendar:
No missing values

Missing values in df_weekly_slots:
No missing values

Missing values in df_lessons:
sibling_group_id    5087
dtype: int64

Missing values in df_payments:
payment_date    611
dtype: int64

In [132]:
print("Unique tutors in students assignment:", df_students["assigned_tutor_id"].nunique())
print("Unique tutors in lessons:", df_lessons["tutor_id"].nunique())
print("Unique students in lessons:", df_lessons["student_id"].nunique())
print("Payment rows vs lesson rows:", len(df_payments), len(df_lessons))

Unique tutors in students assignment: 5
Unique tutors in lessons: 5
Unique students in lessons: 125
Payment rows vs lesson rows: 6550 6550

In [133]:
print("Lesson statuses:")
print(df_lessons["status"].value_counts())
print()

print("Lesson modes:")
print(df_lessons["mode"].value_counts())
print()

print("Payment statuses:")
print(df_payments["payment_status"].value_counts())
print()

print("Average final lesson price:")
print(round(df_lessons["final_price"].mean(), 2))

Lesson statuses:
status
completed               5739
cancelled_by_student     462
no_show                  217
cancelled_by_tutor       132
Name: count, dtype: int64

Lesson modes:
mode
in_person    3666
online       2884
Name: count, dtype: int64

Payment statuses:
payment_status
paid       5162
late        555
missing     479
partial     222
waived      132
Name: count, dtype: int64

Average final lesson price:
110.27

In [135]:
df_tutors.to_csv(DATA_CLEAN / "tutors_clean.csv", index=False, encoding="utf-8-sig")
df_students.to_csv(DATA_CLEAN / "students_clean.csv", index=False, encoding="utf-8-sig")
df_tutor_availability.to_csv(DATA_CLEAN / "tutor_availability_clean.csv", index=False, encoding="utf-8-sig")
df_student_availability.to_csv(DATA_CLEAN / "student_availability_clean.csv", index=False, encoding="utf-8-sig")
df_calendar.to_csv(DATA_CLEAN / "calendar_clean.csv", index=False, encoding="utf-8-sig")
df_weekly_slots.to_csv(DATA_CLEAN / "weekly_slots_clean.csv", index=False, encoding="utf-8-sig")
df_lessons.to_csv(DATA_CLEAN / "lessons_clean.csv", index=False, encoding="utf-8-sig")
df_payments.to_csv(DATA_CLEAN / "payments_clean.csv", index=False, encoding="utf-8-sig")

print("All cleaned files have been saved to the 'data_clean' folder")

All cleaned files have been saved to the 'data_clean' folder

## 13. Data Dictionary

This section creates a simple data dictionary describing the key variables included in the cleaned dataset outputs.

In [136]:
data_dictionary = pd.DataFrame({
    "table_name": [
        "tutors", "students", "tutor_availability", "student_availability",
        "calendar", "weekly_slots", "lessons", "payments"
    ],
    "description": [
        "Tutor master data",
        "Student master data with learning profile",
        "Tutor weekly availability by day and time block",
        "Student weekly availability by day and time block",
        "Calendar table with holidays and working-day flags",
        "Assigned recurring weekly lesson slots",
        "Detailed lesson-level fact table",
        "Payment-level table linked to lessons"
    ]
})

data_dictionary

             table_name                                        description
0                tutors                                  Tutor master data
1              students          Student master data with learning profile
2    tutor_availability    Tutor weekly availability by day and time block
3  student_availability  Student weekly availability by day and time block
4              calendar  Calendar table with holidays and working-day f...
5          weekly_slots             Assigned recurring weekly lesson slots
6               lessons                   Detailed lesson-level fact table
7              payments              Payment-level table linked to lessons

In [137]:
data_dictionary.to_csv(DATA_CLEAN / "data_dictionary.csv", index=False, encoding="utf-8-sig")
print("Data dictionary saved")

Data dictionary saved

## 14. Business Summary Outputs

This final section generates summary tables and headline business metrics.

These outputs provide a starting point for further analysis of:
- expected and realised revenue
- cancellations and no-shows
- tutor workload
- student group performance
- payment status

In [138]:
expected_revenue = df_lessons["final_price"].sum()
actual_revenue = df_payments["amount_paid"].sum()
revenue_leakage = expected_revenue - actual_revenue

print("Expected revenue:", round(expected_revenue, 2))
print("Actual revenue:", round(actual_revenue, 2))
print("Revenue leakage:", round(revenue_leakage, 2))

Expected revenue: 722288.95
Actual revenue: 642511.67
Revenue leakage: 79777.28

In [139]:
print("Total lessons:", len(df_lessons))
print()
print("Lesson status breakdown:")
print(df_lessons["status"].value_counts())
print()
print("Mode breakdown:")
print(df_lessons["mode"].value_counts())

Total lessons: 6550

Lesson status breakdown:
status
completed               5739
cancelled_by_student     462
no_show                  217
cancelled_by_tutor       132
Name: count, dtype: int64

Mode breakdown:
mode
in_person    3666
online       2884
Name: count, dtype: int64

In [140]:
cancelled_lessons = df_lessons["status"].isin(["cancelled_by_student", "cancelled_by_tutor", "no_show"]).sum()
total_lessons = len(df_lessons)
cancellation_rate = cancelled_lessons / total_lessons

print("Cancelled / not completed lessons:", cancelled_lessons)
print("Cancellation / disruption rate:", round(cancellation_rate * 100, 2), "%")

Cancelled / not completed lessons: 811
Cancellation / disruption rate: 12.38 %

In [141]:
tutor_workload = df_lessons.groupby(["tutor_id", "tutor_name"]).agg(
    total_lessons=("lesson_id", "count"),
    total_teaching_minutes=("duration_minutes", "sum"),
    avg_price=("final_price", "mean")
).reset_index()

tutor_workload["total_teaching_hours"] = (tutor_workload["total_teaching_minutes"] / 60).round(2)

tutor_workload.sort_values("total_lessons", ascending=False)

,tutor_id,tutor_name,total_lessons,total_teaching_minutes,avg_price,total_teaching_hours
0,1,Borys Podleśna,2166,142170,126.270360,2369.50
1,2,Łukasz Wac,2124,136170,101.500942,2269.50
3,4,Norbert Durlej,1249,83130,114.122138,1385.50
4,5,Emil Ofiara,508,36810,79.847539,613.50
2,3,Mikołaj Boduch,503,33285,99.598907,554.75

In [142]:
tutor_revenue = df_lessons.groupby(["tutor_id", "tutor_name"]).agg(
    expected_revenue=("final_price", "sum")
).reset_index()

actual_by_tutor = df_lessons.merge(
    df_payments[["lesson_id", "amount_paid"]],
    on="lesson_id",
    how="left"
).groupby(["tutor_id", "tutor_name"]).agg(
    actual_revenue=("amount_paid", "sum")
).reset_index()

tutor_revenue_summary = tutor_revenue.merge(actual_by_tutor, on=["tutor_id", "tutor_name"])
tutor_revenue_summary["revenue_gap"] = (
    tutor_revenue_summary["expected_revenue"] - tutor_revenue_summary["actual_revenue"]
).round(2)

tutor_revenue_summary.sort_values("expected_revenue", ascending=False)

   tutor_id      tutor_name  expected_revenue  actual_revenue  revenue_gap
0         1  Borys Podleśna         273501.60       243837.00     29664.60
1         2      Łukasz Wac         215588.00       191762.50     23825.50
3         4  Norbert Durlej         142538.55       127243.01     15295.54
2         3  Mikołaj Boduch          50098.25        44023.95      6074.30
4         5     Emil Ofiara          40562.55        35645.21      4917.34

In [143]:
age_group_summary = df_lessons.groupby("age_group").agg(
    total_lessons=("lesson_id", "count"),
    avg_price=("final_price", "mean"),
    total_revenue=("final_price", "sum")
).reset_index()

age_group_summary.sort_values("total_revenue", ascending=False)

   age_group  total_lessons   avg_price  total_revenue
3   pre_teen           1637  107.751283      176388.85
4       teen           1537  111.972772      172102.15
1      child           1707   97.351640      166179.25
2  exam_prep            830  146.001084      121180.90
0      adult            839  103.024791       86437.80

In [144]:
mode_summary = df_lessons.groupby("mode").agg(
    total_lessons=("lesson_id", "count"),
    avg_price=("final_price", "mean"),
    total_revenue=("final_price", "sum"),
    avg_travel_time=("travel_time_minutes", "mean")
).reset_index()

mode_summary

        mode  total_lessons   avg_price  total_revenue  avg_travel_time
0  in_person           3666  113.679801      416750.15        24.729951
1     online           2884  105.942718      305538.80         0.000000

In [145]:
payment_summary = df_payments.groupby("payment_status").agg(
    count=("payment_id", "count"),
    total_due=("amount_due", "sum"),
    total_paid=("amount_paid", "sum")
).reset_index()

payment_summary

  payment_status  count  total_due  total_paid
0           late    555   61812.35    61812.35
1        missing    479   53151.50        0.00
2           paid   5162  568300.95   568300.95
3        partial    222   24796.85    12398.37
4         waived    132   14227.30        0.00

In [146]:
monthly_summary = df_lessons.groupby(["year", "month", "month_name"]).agg(
    total_lessons=("lesson_id", "count"),
    expected_revenue=("final_price", "sum")
).reset_index()

monthly_actual = df_lessons.merge(
    df_payments[["lesson_id", "amount_paid"]],
    on="lesson_id",
    how="left"
).groupby(["year", "month", "month_name"]).agg(
    actual_revenue=("amount_paid", "sum")
).reset_index()

monthly_summary = monthly_summary.merge(
    monthly_actual,
    on=["year", "month", "month_name"],
    how="left"
)

monthly_summary["revenue_gap"] = (
    monthly_summary["expected_revenue"] - monthly_summary["actual_revenue"]
).round(2)

monthly_summary.sort_values(["year", "month"])

,year,month,month_name,total_lessons,expected_revenue,actual_revenue,revenue_gap
0,2025,9,September,689,75984.40,67403.75,8580.65
1,2025,10,October,712,78661.20,71231.00,7430.20
2,2025,11,November,605,66727.05,60018.62,6708.43
3,2025,12,December,636,69843.10,62840.17,7002.93
4,2026,1,January,641,70659.05,61538.49,9120.56
5,2026,2,February,628,69325.20,59433.29,9891.91
6,2026,3,March,689,75984.40,67120.40,8864.00
7,2026,4,April,650,72004.25,65168.18,6836.07
8,2026,5,May,640,70661.30,63808.75,6852.55
9,2026,6,June,660,72439.00,63949.02,8489.98

In [147]:
tutor_workload.to_csv(DATA_CLEAN / "summary_tutor_workload.csv", index=False, encoding="utf-8-sig")
tutor_revenue_summary.to_csv(DATA_CLEAN / "summary_tutor_revenue.csv", index=False, encoding="utf-8-sig")
age_group_summary.to_csv(DATA_CLEAN / "summary_age_group.csv", index=False, encoding="utf-8-sig")
mode_summary.to_csv(DATA_CLEAN / "summary_mode.csv", index=False, encoding="utf-8-sig")
payment_summary.to_csv(DATA_CLEAN / "summary_payment.csv", index=False, encoding="utf-8-sig")
monthly_summary.to_csv(DATA_CLEAN / "summary_monthly.csv", index=False, encoding="utf-8-sig")

print("Summary files saved.")

Summary files saved.

## Final Summary

This dataset simulates a real tutoring business environment, including tutor capacity, student demand, and scheduling constraints.

It provides a strong foundation for further analysis such as:
- lesson scheduling optimisation
- revenue and utilisation analysis
- cancellation and attendance patterns
- tutor workload balancing

The structure reflects real-world operational complexity rather than simplified academic examples.