# Tutoring Business Analysis

In [ ]:
import pandas as pd
import numpy as np
from faker import Faker
from pathlib import Path

fake = Faker("pl_PL")

BASE_DIR = Path.cwd().parent
DATA_RAW = BASE_DIR / "data_raw"

print("działa w jupyterze")

działa w jupyterze

In [ ]:
from pathlib import Path

BASE_DIR = Path.cwd().parent
DATA_RAW = BASE_DIR / "data_raw"
DATA_CLEAN = BASE_DIR / "data_clean"

# upewnij się, że folder istnieje
DATA_CLEAN.mkdir(exist_ok=True)

print("DATA_CLEAN path:", DATA_CLEAN)

DATA_CLEAN path: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_clean

In [ ]:
tutors = [
    {
        "tutor_id": 1,
        "tutor_name": fake.name(),
        "experience_level": "senior",
        "hourly_rate": 120,
        "max_weekly_hours": 26,
        "preferred_mode": "mixed",
        "home_area": "Warsaw"
    },
    {
        "tutor_id": 2,
        "tutor_name": fake.name(),
        "experience_level": "mid",
        "hourly_rate": 100,
        "max_weekly_hours": 23,
        "preferred_mode": "mixed",
        "home_area": "Warsaw"
    },
    {
        "tutor_id": 3,
        "tutor_name": fake.name(),
        "experience_level": "mid",
        "hourly_rate": 95,
        "max_weekly_hours": 21,
        "preferred_mode": "online",
        "home_area": "Warsaw"
    },
    {
        "tutor_id": 4,
        "tutor_name": fake.name(),
        "experience_level": "senior",
        "hourly_rate": 110,
        "max_weekly_hours": 26,
        "preferred_mode": "in_person",
        "home_area": "Warsaw"
    },
    {
        "tutor_id": 5,
        "tutor_name": fake.name(),
        "experience_level": "junior",
        "hourly_rate": 70,
        "max_weekly_hours": 13,
        "preferred_mode": "online",
        "home_area": "Warsaw"
    }
]

df_tutors = pd.DataFrame(tutors)
df_tutors

,tutor_id,tutor_name,experience_level,hourly_rate,max_weekly_hours,preferred_mode,home_area
0,1,Marcin Szymków,senior,120,26,mixed,Warsaw
1,2,pani Agnieszka Słomiany,mid,100,23,mixed,Warsaw
2,3,Elżbieta Borysiuk,mid,95,21,online,Warsaw
3,4,pani Bianka Kolanko,senior,110,26,in_person,Warsaw
4,5,pani Aurelia Malcherek,junior,70,13,online,Warsaw

In [ ]:
file_path = DATA_RAW / "tutors.csv"

df_tutors.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zapisano:", file_path)

Zapisano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\tutors.csv

In [ ]:
import random

students = []

age_groups = ["child", "pre_teen", "teen", "exam_prep", "adult"]
cefr_levels = ["A1", "A2", "B1", "B2", "C1"]
learning_goals = ["school", "matura_basic", "matura_extended", "conversation", "general"]
modes = ["online", "in_person"]

for i in range(1, 126):
    student = {
        "student_id": i,
        "student_name": fake.name(),
        "age_group": random.choice(age_groups),
        "cefr_level": random.choice(cefr_levels),
        "learning_goal": random.choice(learning_goals),
        "preferred_mode": random.choice(modes),
        "home_area": "Warsaw",
        "sibling_group_id": None,  # na razie puste
        "start_month": random.choice([9,10,11,12,1,2,3,4,5,6])
    }
    students.append(student)

df_students = pd.DataFrame(students)

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month
0,1,Ignacy Pośnik,child,A1,general,online,Warsaw,None,12
1,2,Witold Pogorzelec,teen,B1,matura_extended,online,Warsaw,None,2
2,3,pan Olaf Jonik,pre_teen,C1,matura_basic,in_person,Warsaw,None,9
3,4,Oskar Roda,adult,B1,matura_basic,in_person,Warsaw,None,12
4,5,Wojciech Habdas,adult,B2,matura_extended,in_person,Warsaw,None,1

In [ ]:
file_path = DATA_RAW / "students.csv"

df_students.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zapisano:", file_path)

Zapisano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\students.csv

In [ ]:
students = []

for i in range(1, 126):

    age_group = random.choices(
        ["child", "pre_teen", "teen", "exam_prep", "adult"],
        weights=[25, 25, 30, 10, 10]
    )[0]

    # CEFR zależny od wieku
    if age_group == "child":
        cefr = random.choice(["A1", "A2"])
    elif age_group == "pre_teen":
        cefr = random.choice(["A1", "A2", "B1"])
    elif age_group == "teen":
        cefr = random.choice(["A2", "B1"])
    elif age_group == "exam_prep":
        cefr = random.choice(["B1", "B2"])
    else:
        cefr = random.choice(["B1", "B2", "C1"])

    # learning goal logic
    if age_group in ["child", "pre_teen"]:
        goal = "school"
    elif age_group == "exam_prep":
        goal = random.choice(["matura_basic", "matura_extended"])
    elif age_group == "teen":
        goal = random.choice(["school", "matura_basic"])
    else:
        goal = random.choice(["conversation", "general"])

    student = {
        "student_id": i,
        "student_name": fake.name(),
        "age_group": age_group,
        "cefr_level": cefr,
        "learning_goal": goal,
        "preferred_mode": random.choice(["online", "in_person"]),
        "home_area": "Warsaw",
        "sibling_group_id": None,
        "start_month": random.choice([9,10,11,12,1,2,3,4,5,6])
    }

    students.append(student)

df_students = pd.DataFrame(students)

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month
0,1,Dariusz Bareja,child,A1,school,online,Warsaw,None,2
1,2,Borys Owczarczak,pre_teen,A2,school,in_person,Warsaw,None,3
2,3,Ryszard Welenc,child,A1,school,online,Warsaw,None,1
3,4,Ewelina Postawa,teen,B1,matura_basic,in_person,Warsaw,None,2
4,5,Franciszek Matus,teen,A2,matura_basic,online,Warsaw,None,2

In [ ]:
file_path = DATA_RAW / "students.csv"

df_students.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zaktualizowano:", file_path)

Zaktualizowano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\students.csv

In [ ]:
df_students = df_students.copy()

df_students["sibling_group_id"] = pd.NA

num_students = len(df_students)
target_share = 0.20  # około 20% uczniów ma rodzeństwo
target_count = int(num_students * target_share)

available_ids = df_students["student_id"].tolist()
random.shuffle(available_ids)

group_id = 1
assigned_count = 0
idx = 0

while assigned_count < target_count and idx < len(available_ids) - 1:
    # większość grup to 2 osoby, czasem 3
    group_size = random.choices([2, 3], weights=[85, 15])[0]

    group_members = available_ids[idx:idx + group_size]

    if len(group_members) < 2:
        break

    df_students.loc[df_students["student_id"].isin(group_members), "sibling_group_id"] = group_id

    assigned_count += len(group_members)
    idx += group_size
    group_id += 1

df_students.head(10)

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month
0,1,Dariusz Bareja,child,A1,school,online,Warsaw,<NA>,2
1,2,Borys Owczarczak,pre_teen,A2,school,in_person,Warsaw,9,3
2,3,Ryszard Welenc,child,A1,school,online,Warsaw,<NA>,1
3,4,Ewelina Postawa,teen,B1,matura_basic,in_person,Warsaw,<NA>,2
4,5,Franciszek Matus,teen,A2,matura_basic,online,Warsaw,11,2
5,6,Juliusz Mejer,pre_teen,B1,school,in_person,Warsaw,<NA>,12
6,7,Adam Kozdra,teen,A2,matura_basic,online,Warsaw,<NA>,11
7,8,Ewelina Strzoda,child,A2,school,in_person,Warsaw,<NA>,3
8,9,pan Łukasz Szramka,pre_teen,A1,school,online,Warsaw,5,4
9,10,Adrianna Pielech,teen,A2,school,in_person,Warsaw,<NA>,6

In [ ]:
df_students["sibling_group_id"].value_counts(dropna=False).head(15)

sibling_group_id
<NA>    100
7         3
9         2
11        2
5         2
12        2
2         2
8         2
10        2
3         2
4         2
1         2
6         2
Name: count, dtype: int64

In [ ]:
df_students[df_students["sibling_group_id"].notna()].sort_values("sibling_group_id").head(20)

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month
88,89,Kalina Walo,adult,B1,conversation,in_person,Warsaw,1,10
78,79,pan Jakub Sakwa,teen,A2,matura_basic,online,Warsaw,1,10
12,13,pani Klara Sinkiewicz,child,A2,school,in_person,Warsaw,2,4
29,30,pan Oliwier Bernatek,adult,C1,general,in_person,Warsaw,2,9
73,74,pani Apolonia Pusz,pre_teen,A1,school,online,Warsaw,3,11
55,56,pan Bartek Cich,teen,A2,matura_basic,in_person,Warsaw,3,12
119,120,Apolonia Kondej,pre_teen,A2,school,in_person,Warsaw,4,5
57,58,Tomasz Klinger,pre_teen,B1,school,in_person,Warsaw,4,5
56,57,Sandra Famuła,exam_prep,B1,matura_extended,in_person,Warsaw,5,2
8,9,pan Łukasz Szramka,pre_teen,A1,school,online,Warsaw,5,4
104,105,Melania Suchora,child,A2,school,in_person,Warsaw,6,12
123,124,Tymoteusz Szmalec,pre_teen,A1,school,in_person,Warsaw,6,1
58,59,pan Gustaw Panasiewicz,child,A1,school,in_person,Warsaw,7,11
107,108,Mieszko Fugiel,adult,B1,conversation,in_person,Warsaw,7,2
48,49,Agnieszka Wawrzynek,teen,A2,matura_basic,online,Warsaw,7,5
37,38,Ada Bartocha,adult,B2,conversation,in_person,Warsaw,8,1
75,76,Marcelina Bernard,pre_teen,A1,school,online,Warsaw,8,9
122,123,Igor Miśkowiec,teen,A2,matura_basic,in_person,Warsaw,9,1
1,2,Borys Owczarczak,pre_teen,A2,school,in_person,Warsaw,9,3
47,48,Inga Pyc,pre_teen,A2,school,in_person,Warsaw,10,6

In [ ]:
file_path = DATA_RAW / "students.csv"

df_students.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zaktualizowano:", file_path)

Zaktualizowano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\students.csv

In [ ]:
weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
time_blocks = [
    "08:00-09:00",
    "09:00-10:00",
    "10:00-11:00",
    "11:00-12:00",
    "12:00-13:00",
    "13:00-14:00",
    "14:00-15:00",
    "15:00-16:00",
    "16:00-17:00",
    "17:00-18:00",
    "18:00-19:00",
    "19:00-20:00",
    "20:00-21:00"
]

tutor_availability = []
availability_id = 1

In [ ]:
for _, tutor in df_tutors.iterrows():
    tutor_id = tutor["tutor_id"]
    preferred_mode = tutor["preferred_mode"]
    max_hours = tutor["max_weekly_hours"]

    for day in weekdays:
        for block in time_blocks:

            start_hour = int(block.split(":")[0])

            # bazowa logika dostępności
            if tutor_id == 5:
                # studentka - mniej godzin, głównie popołudnia i wieczory
                available = 1 if day in ["Monday", "Wednesday", "Friday", "Saturday"] and start_hour >= 15 else 0

            elif tutor_id == 3:
                # online tutor - głównie popołudnia, bez sobotnich poranków
                available = 1 if start_hour >= 14 and day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] else 0

            elif tutor_id == 4:
                # in-person tutor - bardziej klasyczny grafik
                available = 1 if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] and 10 <= start_hour <= 18 else 0

            else:
                # mixed tutors
                available = 1 if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] and 12 <= start_hour <= 20 else 0

            tutor_availability.append({
                "availability_id": availability_id,
                "tutor_id": tutor_id,
                "weekday": day,
                "time_block": block,
                "available_flag": available
            })

            availability_id += 1

df_tutor_availability = pd.DataFrame(tutor_availability)
df_tutor_availability.head(20)

    availability_id  tutor_id  weekday   time_block  available_flag
0                 1         1   Monday  08:00-09:00               0
1                 2         1   Monday  09:00-10:00               0
2                 3         1   Monday  10:00-11:00               0
3                 4         1   Monday  11:00-12:00               0
4                 5         1   Monday  12:00-13:00               1
5                 6         1   Monday  13:00-14:00               1
6                 7         1   Monday  14:00-15:00               1
7                 8         1   Monday  15:00-16:00               1
8                 9         1   Monday  16:00-17:00               1
9                10         1   Monday  17:00-18:00               1
10               11         1   Monday  18:00-19:00               1
11               12         1   Monday  19:00-20:00               1
12               13         1   Monday  20:00-21:00               1
13               14         1  Tuesday  08:00-09:00               0
14               15         1  Tuesday  09:00-10:00               0
15               16         1  Tuesday  10:00-11:00               0
16               17         1  Tuesday  11:00-12:00               0
17               18         1  Tuesday  12:00-13:00               1
18               19         1  Tuesday  13:00-14:00               1
19               20         1  Tuesday  14:00-15:00               1

In [ ]:
df_tutor_availability[df_tutor_availability["available_flag"] == 1].groupby("tutor_id").size()

tutor_id
1    54
2    54
3    35
4    54
5    24
dtype: int64

In [ ]:
file_path = DATA_RAW / "tutor_availability.csv"

df_tutor_availability.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zapisano:", file_path)

Zapisano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\tutor_availability.csv

In [ ]:
student_availability = []
availability_id = 1

In [ ]:
for _, student in df_students.iterrows():
    student_id = student["student_id"]
    age_group = student["age_group"]

    for day in weekdays:
        for block in time_blocks:
            start_hour = int(block.split(":")[0])

            # domyślnie niedostępny
            available = 0

            if age_group == "child":
                # dzieci: głównie po szkole, trochę soboty
                if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] and 15 <= start_hour <= 18:
                    available = 1 if random.random() < 0.75 else 0
                elif day == "Saturday" and 9 <= start_hour <= 13:
                    available = 1 if random.random() < 0.50 else 0

            elif age_group == "pre_teen":
                # starsze dzieci: po szkole + trochę później
                if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] and 15 <= start_hour <= 19:
                    available = 1 if random.random() < 0.70 else 0
                elif day == "Saturday" and 9 <= start_hour <= 14:
                    available = 1 if random.random() < 0.45 else 0

            elif age_group == "teen":
                # nastolatki: popołudnia i wieczory
                if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] and 16 <= start_hour <= 20:
                    available = 1 if random.random() < 0.68 else 0
                elif day == "Saturday" and 10 <= start_hour <= 15:
                    available = 1 if random.random() < 0.35 else 0

            elif age_group == "exam_prep":
                # maturzyści: późniejsze godziny, często też sobota
                if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] and 17 <= start_hour <= 20:
                    available = 1 if random.random() < 0.72 else 0
                elif day == "Saturday" and 10 <= start_hour <= 16:
                    available = 1 if random.random() < 0.40 else 0

            elif age_group == "adult":
                # dorośli: głównie wieczory, czasem poranek/sobota
                if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] and 18 <= start_hour <= 20:
                    available = 1 if random.random() < 0.75 else 0
                elif day == "Saturday" and 9 <= start_hour <= 13:
                    available = 1 if random.random() < 0.30 else 0

            student_availability.append({
                "availability_id": availability_id,
                "student_id": student_id,
                "weekday": day,
                "time_block": block,
                "available_flag": available
            })

            availability_id += 1

df_student_availability = pd.DataFrame(student_availability)
df_student_availability.head(20)

    availability_id  student_id  weekday   time_block  available_flag
0                 1           1   Monday  08:00-09:00               0
1                 2           1   Monday  09:00-10:00               0
2                 3           1   Monday  10:00-11:00               0
3                 4           1   Monday  11:00-12:00               0
4                 5           1   Monday  12:00-13:00               0
5                 6           1   Monday  13:00-14:00               0
6                 7           1   Monday  14:00-15:00               0
7                 8           1   Monday  15:00-16:00               1
8                 9           1   Monday  16:00-17:00               1
9                10           1   Monday  17:00-18:00               1
10               11           1   Monday  18:00-19:00               1
11               12           1   Monday  19:00-20:00               0
12               13           1   Monday  20:00-21:00               0
13               14           1  Tuesday  08:00-09:00               0
14               15           1  Tuesday  09:00-10:00               0
15               16           1  Tuesday  10:00-11:00               0
16               17           1  Tuesday  11:00-12:00               0
17               18           1  Tuesday  12:00-13:00               0
18               19           1  Tuesday  13:00-14:00               0
19               20           1  Tuesday  14:00-15:00               0

In [ ]:
df_student_availability[df_student_availability["available_flag"] == 1].groupby("student_id").size().describe()

count    125.000000
mean      17.984000
std        3.428966
min        9.000000
25%       16.000000
50%       18.000000
75%       21.000000
max       25.000000
dtype: float64

In [ ]:
sample_students = df_students[["student_id", "age_group"]].head(5)
sample_students

   student_id age_group
0           1     child
1           2  pre_teen
2           3     child
3           4      teen
4           5      teen

In [ ]:
df_student_availability[
    df_student_availability["student_id"].isin(sample_students["student_id"])
].sort_values(["student_id", "weekday", "time_block"]).head(50)

    availability_id  student_id   weekday   time_block  available_flag
52               53           1    Friday  08:00-09:00               0
53               54           1    Friday  09:00-10:00               0
54               55           1    Friday  10:00-11:00               0
55               56           1    Friday  11:00-12:00               0
56               57           1    Friday  12:00-13:00               0
57               58           1    Friday  13:00-14:00               0
58               59           1    Friday  14:00-15:00               0
59               60           1    Friday  15:00-16:00               0
60               61           1    Friday  16:00-17:00               0
61               62           1    Friday  17:00-18:00               1
62               63           1    Friday  18:00-19:00               0
63               64           1    Friday  19:00-20:00               0
64               65           1    Friday  20:00-21:00               0
0                 1           1    Monday  08:00-09:00               0
1                 2           1    Monday  09:00-10:00               0
2                 3           1    Monday  10:00-11:00               0
3                 4           1    Monday  11:00-12:00               0
4                 5           1    Monday  12:00-13:00               0
5                 6           1    Monday  13:00-14:00               0
6                 7           1    Monday  14:00-15:00               0
7                 8           1    Monday  15:00-16:00               1
8                 9           1    Monday  16:00-17:00               1
9                10           1    Monday  17:00-18:00               1
10               11           1    Monday  18:00-19:00               1
11               12           1    Monday  19:00-20:00               0
12               13           1    Monday  20:00-21:00               0
65               66           1  Saturday  08:00-09:00               0
66               67           1  Saturday  09:00-10:00               0
67               68           1  Saturday  10:00-11:00               1
68               69           1  Saturday  11:00-12:00               1
69               70           1  Saturday  12:00-13:00               0
70               71           1  Saturday  13:00-14:00               0
71               72           1  Saturday  14:00-15:00               0
72               73           1  Saturday  15:00-16:00               0
73               74           1  Saturday  16:00-17:00               0
74               75           1  Saturday  17:00-18:00               0
75               76           1  Saturday  18:00-19:00               0
76               77           1  Saturday  19:00-20:00               0
77               78           1  Saturday  20:00-21:00               0
39               40           1  Thursday  08:00-09:00               0
40               41           1  Thursday  09:00-10:00               0
41               42           1  Thursday  10:00-11:00               0
42               43           1  Thursday  11:00-12:00               0
43               44           1  Thursday  12:00-13:00               0
44               45           1  Thursday  13:00-14:00               0
45               46           1  Thursday  14:00-15:00               0
46               47           1  Thursday  15:00-16:00               1
47               48           1  Thursday  16:00-17:00               1
48               49           1  Thursday  17:00-18:00               1
49               50           1  Thursday  18:00-19:00               1

In [ ]:
file_path = DATA_RAW / "student_availability.csv"

df_student_availability.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zapisano:", file_path)

Zapisano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\student_availability.csv

In [ ]:
calendar_dates = pd.date_range(start="2025-09-01", end="2026-06-30", freq="D")

df_calendar = pd.DataFrame({"date": calendar_dates})
df_calendar.head()

        date
0 2025-09-01
1 2025-09-02
2 2025-09-03
3 2025-09-04
4 2025-09-05

In [ ]:
df_calendar["year"] = df_calendar["date"].dt.year
df_calendar["month"] = df_calendar["date"].dt.month
df_calendar["month_name"] = df_calendar["date"].dt.month_name()
df_calendar["weekday"] = df_calendar["date"].dt.day_name()
df_calendar["is_weekend"] = df_calendar["weekday"].isin(["Saturday", "Sunday"]).astype(int)

df_calendar.head()

        date  year  month month_name    weekday  is_weekend
0 2025-09-01  2025      9  September     Monday           0
1 2025-09-02  2025      9  September    Tuesday           0
2 2025-09-03  2025      9  September  Wednesday           0
3 2025-09-04  2025      9  September   Thursday           0
4 2025-09-05  2025      9  September     Friday           0

In [ ]:
holidays = [
    "2025-11-01",  # Wszystkich Świętych
    "2025-11-11",  # Niepodległość
    "2025-12-24",  # Wigilia
    "2025-12-25",  # Boże Narodzenie
    "2025-12-26",  # Boże Narodzenie
    "2026-01-01",  # Nowy Rok
    "2026-01-06",  # Trzech Króli
    "2026-04-05",  # Wielkanoc
    "2026-04-06",  # Poniedziałek Wielkanocny
    "2026-05-01",  # Święto Pracy
    "2026-05-03",  # Konstytucja 3 Maja
    "2026-06-04"   # Boże Ciało
]

df_calendar["is_holiday"] = df_calendar["date"].astype(str).isin(holidays).astype(int)
df_calendar.head()

        date  year  month month_name    weekday  is_weekend  is_holiday
0 2025-09-01  2025      9  September     Monday           0           0
1 2025-09-02  2025      9  September    Tuesday           0           0
2 2025-09-03  2025      9  September  Wednesday           0           0
3 2025-09-04  2025      9  September   Thursday           0           0
4 2025-09-05  2025      9  September     Friday           0           0

In [ ]:
df_calendar["is_working_day"] = ((df_calendar["is_weekend"] == 0) & (df_calendar["is_holiday"] == 0)).astype(int)

# peak months = październik–maj
df_calendar["is_peak_month"] = df_calendar["month"].isin([10, 11, 12, 1, 2, 3, 4, 5]).astype(int)

df_calendar.head()

,date,year,month,month_name,weekday,is_weekend,is_holiday,is_working_day,is_peak_month
0,2025-09-01,2025,9,September,Monday,0,0,1,0
1,2025-09-02,2025,9,September,Tuesday,0,0,1,0
2,2025-09-03,2025,9,September,Wednesday,0,0,1,0
3,2025-09-04,2025,9,September,Thursday,0,0,1,0
4,2025-09-05,2025,9,September,Friday,0,0,1,0

In [ ]:
df_calendar.sample(10).sort_values("date")

,date,year,month,month_name,weekday,is_weekend,is_holiday,is_working_day,is_peak_month
40,2025-10-11,2025,10,October,Saturday,1,0,0,1
82,2025-11-22,2025,11,November,Saturday,1,0,0,1
104,2025-12-14,2025,12,December,Sunday,1,0,0,1
160,2026-02-08,2026,2,February,Sunday,1,0,0,1
217,2026-04-06,2026,4,April,Monday,0,1,0,1
226,2026-04-15,2026,4,April,Wednesday,0,0,1,1
262,2026-05-21,2026,5,May,Thursday,0,0,1,1
269,2026-05-28,2026,5,May,Thursday,0,0,1,1
274,2026-06-02,2026,6,June,Tuesday,0,0,1,0
285,2026-06-13,2026,6,June,Saturday,1,0,0,0

In [ ]:
df_calendar[df_calendar["is_holiday"] == 1].sort_values("date")

,date,year,month,month_name,weekday,is_weekend,is_holiday,is_working_day,is_peak_month
61,2025-11-01,2025,11,November,Saturday,1,1,0,1
71,2025-11-11,2025,11,November,Tuesday,0,1,0,1
114,2025-12-24,2025,12,December,Wednesday,0,1,0,1
115,2025-12-25,2025,12,December,Thursday,0,1,0,1
116,2025-12-26,2025,12,December,Friday,0,1,0,1
122,2026-01-01,2026,1,January,Thursday,0,1,0,1
127,2026-01-06,2026,1,January,Tuesday,0,1,0,1
216,2026-04-05,2026,4,April,Sunday,1,1,0,1
217,2026-04-06,2026,4,April,Monday,0,1,0,1
242,2026-05-01,2026,5,May,Friday,0,1,0,1
244,2026-05-03,2026,5,May,Sunday,1,1,0,1
276,2026-06-04,2026,6,June,Thursday,0,1,0,0

In [ ]:
file_path = DATA_RAW / "calendar.csv"

df_calendar.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zapisano:", file_path)

Zapisano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\calendar.csv

In [ ]:
df_students = df_students.copy()

In [ ]:
lessons_per_week_list = []

for _, student in df_students.iterrows():
    age_group = student["age_group"]
    learning_goal = student["learning_goal"]

    if age_group == "exam_prep":
        lessons_per_week = random.choices([1, 2], weights=[40, 60])[0]
    elif age_group == "adult":
        lessons_per_week = random.choices([1, 2], weights=[75, 25])[0]
    else:
        lessons_per_week = random.choices([1, 2], weights=[85, 15])[0]

    lessons_per_week_list.append(lessons_per_week)

df_students["lessons_per_week"] = lessons_per_week_list

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week
0,1,Dariusz Bareja,child,A1,school,online,Warsaw,<NA>,2,1
1,2,Borys Owczarczak,pre_teen,A2,school,in_person,Warsaw,9,3,2
2,3,Ryszard Welenc,child,A1,school,online,Warsaw,<NA>,1,1
3,4,Ewelina Postawa,teen,B1,matura_basic,in_person,Warsaw,<NA>,2,1
4,5,Franciszek Matus,teen,A2,matura_basic,online,Warsaw,11,2,1

In [ ]:
durations = []

for _, student in df_students.iterrows():
    age_group = student["age_group"]
    learning_goal = student["learning_goal"]

    if age_group == "child":
        duration = random.choices([45, 60], weights=[45, 55])[0]

    elif age_group == "pre_teen":
        duration = random.choices([45, 60, 90], weights=[20, 65, 15])[0]

    elif age_group == "teen":
        duration = random.choices([60, 90], weights=[75, 25])[0]

    elif age_group == "exam_prep":
        if learning_goal == "matura_extended":
            duration = random.choices([60, 90, 120], weights=[20, 60, 20])[0]
        else:
            duration = random.choices([60, 90], weights=[55, 45])[0]

    else:  # adult
        duration = random.choices([60, 90], weights=[70, 30])[0]

    durations.append(duration)

df_students["typical_duration_minutes"] = durations

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week,typical_duration_minutes
0,1,Dariusz Bareja,child,A1,school,online,Warsaw,<NA>,2,1,45
1,2,Borys Owczarczak,pre_teen,A2,school,in_person,Warsaw,9,3,2,45
2,3,Ryszard Welenc,child,A1,school,online,Warsaw,<NA>,1,1,60
3,4,Ewelina Postawa,teen,B1,matura_basic,in_person,Warsaw,<NA>,2,1,60
4,5,Franciszek Matus,teen,A2,matura_basic,online,Warsaw,11,2,1,60

In [ ]:
assigned_modes = []

for _, student in df_students.iterrows():
    preferred_mode = student["preferred_mode"]
    age_group = student["age_group"]

    if preferred_mode == "online":
        assigned_mode = random.choices(["online", "in_person"], weights=[85, 15])[0]
    elif preferred_mode == "in_person":
        assigned_mode = random.choices(["in_person", "online"], weights=[85, 15])[0]
    else:
        assigned_mode = random.choice(["online", "in_person"])

    # lekkie doprecyzowanie: dzieci częściej stacjonarnie
    if age_group == "child" and assigned_mode == "online":
        assigned_mode = random.choices(["in_person", "online"], weights=[65, 35])[0]

    assigned_modes.append(assigned_mode)

df_students["assigned_mode"] = assigned_modes

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week,typical_duration_minutes,assigned_mode
0,1,Dariusz Bareja,child,A1,school,online,Warsaw,<NA>,2,1,45,in_person
1,2,Borys Owczarczak,pre_teen,A2,school,in_person,Warsaw,9,3,2,45,in_person
2,3,Ryszard Welenc,child,A1,school,online,Warsaw,<NA>,1,1,60,online
3,4,Ewelina Postawa,teen,B1,matura_basic,in_person,Warsaw,<NA>,2,1,60,in_person
4,5,Franciszek Matus,teen,A2,matura_basic,online,Warsaw,11,2,1,60,online

In [ ]:
prep_profiles = []

for _, student in df_students.iterrows():
    age_group = student["age_group"]
    learning_goal = student["learning_goal"]

    if learning_goal == "matura_extended":
        prep_profile = random.choice(["medium", "high"])
    elif learning_goal == "matura_basic":
        prep_profile = random.choice(["low", "medium"])
    elif age_group == "child":
        prep_profile = random.choice(["medium", "high"])
    elif age_group == "adult":
        prep_profile = random.choice(["low", "medium"])
    else:
        prep_profile = random.choice(["low", "medium", "high"])

    prep_profiles.append(prep_profile)

df_students["prep_profile"] = prep_profiles

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week,typical_duration_minutes,assigned_mode,prep_profile
0,1,Dariusz Bareja,child,A1,school,online,Warsaw,<NA>,2,1,45,in_person,high
1,2,Borys Owczarczak,pre_teen,A2,school,in_person,Warsaw,9,3,2,45,in_person,high
2,3,Ryszard Welenc,child,A1,school,online,Warsaw,<NA>,1,1,60,online,medium
3,4,Ewelina Postawa,teen,B1,matura_basic,in_person,Warsaw,<NA>,2,1,60,in_person,low
4,5,Franciszek Matus,teen,A2,matura_basic,online,Warsaw,11,2,1,60,online,low

In [ ]:
df_students[[
    "student_id",
    "age_group",
    "cefr_level",
    "learning_goal",
    "lessons_per_week",
    "typical_duration_minutes",
    "assigned_mode",
    "prep_profile"
]].head(15)

,student_id,age_group,cefr_level,learning_goal,lessons_per_week,typical_duration_minutes,assigned_mode,prep_profile
0,1,child,A1,school,1,45,in_person,high
1,2,pre_teen,A2,school,2,45,in_person,high
2,3,child,A1,school,1,60,online,medium
3,4,teen,B1,matura_basic,1,60,in_person,low
4,5,teen,A2,matura_basic,1,60,online,low
5,6,pre_teen,B1,school,1,60,online,medium
6,7,teen,A2,matura_basic,1,60,online,medium
7,8,child,A2,school,1,60,in_person,high
8,9,pre_teen,A1,school,1,60,online,low
9,10,teen,A2,school,1,60,in_person,low
10,11,pre_teen,A1,school,1,45,in_person,low
11,12,teen,A2,matura_basic,2,90,in_person,medium
12,13,child,A2,school,1,45,in_person,high
13,14,child,A1,school,2,45,in_person,high
14,15,teen,A2,school,1,60,in_person,high

In [ ]:
print("Lessons per week:")
print(df_students["lessons_per_week"].value_counts())
print()

print("Typical duration:")
print(df_students["typical_duration_minutes"].value_counts().sort_index())
print()

print("Assigned mode:")
print(df_students["assigned_mode"].value_counts())
print()

print("Prep profile:")
print(df_students["prep_profile"].value_counts())

Lessons per week:
lessons_per_week
1    92
2    33
Name: count, dtype: int64

Typical duration:
typical_duration_minutes
45    25
60    81
90    19
Name: count, dtype: int64

Assigned mode:
assigned_mode
in_person    85
online       40
Name: count, dtype: int64

Prep profile:
prep_profile
medium    56
high      37
low       32
Name: count, dtype: int64

In [ ]:
file_path = DATA_RAW / "students.csv"

df_students.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zaktualizowano:", file_path)

Zaktualizowano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\students.csv

In [ ]:
df_tutors

,tutor_id,tutor_name,experience_level,hourly_rate,max_weekly_hours,preferred_mode,home_area
0,1,Marcin Szymków,senior,120,26,mixed,Warsaw
1,2,pani Agnieszka Słomiany,mid,100,23,mixed,Warsaw
2,3,Elżbieta Borysiuk,mid,95,21,online,Warsaw
3,4,pani Bianka Kolanko,senior,110,26,in_person,Warsaw
4,5,pani Aurelia Malcherek,junior,70,13,online,Warsaw

In [ ]:
def choose_tutor(student_row, tutors_df):
    age_group = student_row["age_group"]
    learning_goal = student_row["learning_goal"]
    assigned_mode = student_row["assigned_mode"]

    # kopiujemy tutorów do filtrowania
    possible_tutors = tutors_df.copy()

    # 1. tryb
    if assigned_mode == "online":
        filtered = possible_tutors[possible_tutors["preferred_mode"].isin(["online", "mixed"])]
    else:
        filtered = possible_tutors[possible_tutors["preferred_mode"].isin(["in_person", "mixed"])]

    if len(filtered) > 0:
        possible_tutors = filtered

    # 2. exam prep częściej do bardziej doświadczonych
    if age_group == "exam_prep" or learning_goal in ["matura_basic", "matura_extended"]:
        filtered = possible_tutors[possible_tutors["experience_level"].isin(["mid", "senior"])]
        if len(filtered) > 0:
            possible_tutors = filtered

    # 3. adults częściej do online / mixed
    if age_group == "adult":
        filtered = possible_tutors[possible_tutors["preferred_mode"].isin(["online", "mixed"])]
        if len(filtered) > 0:
            possible_tutors = filtered

    # 4. dzieci częściej do mixed / in-person
    if age_group == "child":
        filtered = possible_tutors[possible_tutors["preferred_mode"].isin(["in_person", "mixed"])]
        if len(filtered) > 0:
            possible_tutors = filtered

    # 5. tutor 5 ma mniej uczniów
    tutor_ids = possible_tutors["tutor_id"].tolist()

    weights_map = {
        1: 1.2,
        2: 1.0,
        3: 0.9,
        4: 1.1,
        5: 0.5
    }

    weights = [weights_map[tutor_id] for tutor_id in tutor_ids]

    chosen_tutor_id = random.choices(tutor_ids, weights=weights, k=1)[0]

    return chosen_tutor_id

In [ ]:
assigned_tutor_ids = []

for _, student in df_students.iterrows():
    tutor_id = choose_tutor(student, df_tutors)
    assigned_tutor_ids.append(tutor_id)

df_students["assigned_tutor_id"] = assigned_tutor_ids
df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week,typical_duration_minutes,assigned_mode,prep_profile,assigned_tutor_id
0,1,Dariusz Bareja,child,A1,school,online,Warsaw,<NA>,2,1,45,in_person,high,1
1,2,Borys Owczarczak,pre_teen,A2,school,in_person,Warsaw,9,3,2,45,in_person,high,2
2,3,Ryszard Welenc,child,A1,school,online,Warsaw,<NA>,1,1,60,online,medium,1
3,4,Ewelina Postawa,teen,B1,matura_basic,in_person,Warsaw,<NA>,2,1,60,in_person,low,4
4,5,Franciszek Matus,teen,A2,matura_basic,online,Warsaw,11,2,1,60,online,low,3

In [ ]:
tutor_name_map = dict(zip(df_tutors["tutor_id"], df_tutors["tutor_name"]))

df_students["assigned_tutor_name"] = df_students["assigned_tutor_id"].map(tutor_name_map)

df_students.head()

,student_id,student_name,age_group,cefr_level,learning_goal,preferred_mode,home_area,sibling_group_id,start_month,lessons_per_week,typical_duration_minutes,assigned_mode,prep_profile,assigned_tutor_id,assigned_tutor_name
0,1,Dariusz Bareja,child,A1,school,online,Warsaw,<NA>,2,1,45,in_person,high,1,Marcin Szymków
1,2,Borys Owczarczak,pre_teen,A2,school,in_person,Warsaw,9,3,2,45,in_person,high,2,pani Agnieszka Słomiany
2,3,Ryszard Welenc,child,A1,school,online,Warsaw,<NA>,1,1,60,online,medium,1,Marcin Szymków
3,4,Ewelina Postawa,teen,B1,matura_basic,in_person,Warsaw,<NA>,2,1,60,in_person,low,4,pani Bianka Kolanko
4,5,Franciszek Matus,teen,A2,matura_basic,online,Warsaw,11,2,1,60,online,low,3,Elżbieta Borysiuk

In [ ]:
df_students["assigned_tutor_id"].value_counts().sort_index()

assigned_tutor_id
1    54
2    38
3     7
4    21
5     5
Name: count, dtype: int64

In [ ]:
df_students.groupby(["assigned_tutor_id", "age_group"]).size().unstack(fill_value=0)

age_group          adult  child  exam_prep  pre_teen  teen
assigned_tutor_id
1                      4     13          5        15    17
2                      7      6          3        10    12
3                      0      0          1         1     5
4                      0     11          1         3     6
5                      3      0          0         0     2

In [ ]:
file_path = DATA_RAW / "students.csv"

df_students.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zaktualizowano:", file_path)

Zaktualizowano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\students.csv

In [ ]:
df_tutor_available = df_tutor_availability[df_tutor_availability["available_flag"] == 1].copy()
df_student_available = df_student_availability[df_student_availability["available_flag"] == 1].copy()

In [ ]:
df_tutor_available["slot_key"] = df_tutor_available["weekday"] + "|" + df_tutor_available["time_block"]
df_student_available["slot_key"] = df_student_available["weekday"] + "|" + df_student_available["time_block"]

In [ ]:
def assign_weekly_slots(student_row, df_student_available, df_tutor_available):
    student_id = student_row["student_id"]
    tutor_id = student_row["assigned_tutor_id"]
    lessons_per_week = student_row["lessons_per_week"]

    student_slots = set(
        df_student_available[df_student_available["student_id"] == student_id]["slot_key"]
    )

    tutor_slots = set(
        df_tutor_available[df_tutor_available["tutor_id"] == tutor_id]["slot_key"]
    )

    common_slots = list(student_slots.intersection(tutor_slots))

    if len(common_slots) == 0:
        return []

    # sortowanie
    weekday_order = {
        "Monday": 1,
        "Tuesday": 2,
        "Wednesday": 3,
        "Thursday": 4,
        "Friday": 5,
        "Saturday": 6
    }

    common_slots_sorted = sorted(
        common_slots,
        key=lambda x: (
            weekday_order[x.split("|")[0]],
            x.split("|")[1]
        )
    )

    # los - tyle slotów, ile trzeba
    if len(common_slots_sorted) <= lessons_per_week:
        selected_slots = common_slots_sorted
    else:
        selected_slots = random.sample(common_slots_sorted, lessons_per_week)

    return selected_slots

In [ ]:
weekly_slots = []

for _, student in df_students.iterrows():
    selected_slots = assign_weekly_slots(student, df_student_available, df_tutor_available)

    for slot in selected_slots:
        weekday, time_block = slot.split("|")

        weekly_slots.append({
            "student_id": student["student_id"],
            "assigned_tutor_id": student["assigned_tutor_id"],
            "weekday": weekday,
            "time_block": time_block,
            "assigned_mode": student["assigned_mode"],
            "typical_duration_minutes": student["typical_duration_minutes"],
            "lessons_per_week": student["lessons_per_week"]
        })

df_weekly_slots = pd.DataFrame(weekly_slots)
df_weekly_slots.head(20)

,student_id,assigned_tutor_id,weekday,time_block,assigned_mode,typical_duration_minutes,lessons_per_week
0,1,1,Monday,17:00-18:00,in_person,45,1
1,2,2,Monday,19:00-20:00,in_person,45,2
2,2,2,Wednesday,15:00-16:00,in_person,45,2
3,3,1,Thursday,16:00-17:00,online,60,1
4,4,4,Tuesday,18:00-19:00,in_person,60,1
5,5,3,Thursday,18:00-19:00,online,60,1
6,6,1,Thursday,16:00-17:00,online,60,1
7,7,1,Thursday,19:00-20:00,online,60,1
8,8,4,Friday,16:00-17:00,in_person,60,1
9,9,1,Wednesday,18:00-19:00,online,60,1
10,10,1,Saturday,14:00-15:00,in_person,60,1
11,11,1,Friday,17:00-18:00,in_person,45,1
12,12,4,Friday,16:00-17:00,in_person,90,2
13,12,4,Wednesday,18:00-19:00,in_person,90,2
14,13,1,Thursday,15:00-16:00,in_person,45,1
15,14,1,Thursday,16:00-17:00,in_person,45,2
16,14,1,Wednesday,17:00-18:00,in_person,45,2
17,15,4,Tuesday,17:00-18:00,in_person,60,1
18,16,4,Monday,16:00-17:00,in_person,45,1
19,17,1,Friday,16:00-17:00,in_person,60,1

In [ ]:
assigned_counts = df_weekly_slots.groupby("student_id").size().reset_index(name="assigned_slots")

df_check = df_students[["student_id", "lessons_per_week"]].merge(
    assigned_counts,
    on="student_id",
    how="left"
)

df_check["assigned_slots"] = df_check["assigned_slots"].fillna(0).astype(int)

df_check.head(20)

    student_id  lessons_per_week  assigned_slots
0            1                 1               1
1            2                 2               2
2            3                 1               1
3            4                 1               1
4            5                 1               1
5            6                 1               1
6            7                 1               1
7            8                 1               1
8            9                 1               1
9           10                 1               1
10          11                 1               1
11          12                 2               2
12          13                 1               1
13          14                 2               2
14          15                 1               1
15          16                 1               1
16          17                 1               1
17          18                 2               2
18          19                 1               1
19          20                 2               2

In [ ]:
df_check[df_check["assigned_slots"] < df_check["lessons_per_week"]]

Empty DataFrame
Columns: [student_id, lessons_per_week, assigned_slots]
Index: []

In [ ]:
df_weekly_slots.sort_values(["assigned_tutor_id", "weekday", "time_block"]).head(50)

,student_id,assigned_tutor_id,weekday,time_block,assigned_mode,typical_duration_minutes,lessons_per_week
32,26,1,Friday,15:00-16:00,in_person,90,1
19,17,1,Friday,16:00-17:00,in_person,60,1
11,11,1,Friday,17:00-18:00,in_person,45,1
54,43,1,Friday,17:00-18:00,in_person,60,1
92,73,1,Friday,17:00-18:00,online,60,2
106,86,1,Friday,17:00-18:00,online,45,2
76,60,1,Friday,18:00-19:00,in_person,45,1
28,23,1,Friday,19:00-20:00,online,60,2
131,103,1,Friday,20:00-21:00,in_person,60,2
51,40,1,Monday,16:00-17:00,online,45,2
56,45,1,Monday,16:00-17:00,online,90,1
146,116,1,Monday,16:00-17:00,in_person,90,1
153,122,1,Monday,16:00-17:00,in_person,60,2
0,1,1,Monday,17:00-18:00,in_person,45,1
124,98,1,Monday,17:00-18:00,in_person,45,1
42,34,1,Monday,18:00-19:00,in_person,60,1
46,37,1,Monday,18:00-19:00,in_person,60,1
49,39,1,Monday,18:00-19:00,in_person,90,2
50,40,1,Monday,18:00-19:00,online,45,2
65,52,1,Monday,18:00-19:00,online,60,2
118,93,1,Monday,18:00-19:00,in_person,45,1
58,47,1,Saturday,12:00-13:00,in_person,60,1
142,112,1,Saturday,12:00-13:00,in_person,90,1
26,22,1,Saturday,13:00-14:00,in_person,60,2
104,84,1,Saturday,13:00-14:00,in_person,45,1
10,10,1,Saturday,14:00-15:00,in_person,60,1
64,52,1,Saturday,14:00-15:00,online,60,2
132,103,1,Saturday,14:00-15:00,in_person,60,2
14,13,1,Thursday,15:00-16:00,in_person,45,1
62,50,1,Thursday,15:00-16:00,online,60,1
3,3,1,Thursday,16:00-17:00,online,60,1
6,6,1,Thursday,16:00-17:00,online,60,1
15,14,1,Thursday,16:00-17:00,in_person,45,2
55,44,1,Thursday,16:00-17:00,in_person,60,1
59,48,1,Thursday,16:00-17:00,in_person,60,1
154,122,1,Thursday,16:00-17:00,in_person,60,2
155,123,1,Thursday,16:00-17:00,in_person,60,1
109,88,1,Thursday,17:00-18:00,in_person,90,2
114,90,1,Thursday,17:00-18:00,in_person,60,2
137,107,1,Thursday,17:00-18:00,in_person,60,1
48,39,1,Thursday,18:00-19:00,in_person,90,2
84,66,1,Thursday,18:00-19:00,in_person,60,2
113,90,1,Thursday,18:00-19:00,in_person,60,2
136,106,1,Thursday,18:00-19:00,in_person,60,2
7,7,1,Thursday,19:00-20:00,online,60,1
27,22,1,Thursday,20:00-21:00,in_person,60,2
83,66,1,Thursday,20:00-21:00,in_person,60,2
139,109,1,Thursday,20:00-21:00,in_person,60,1
150,119,1,Tuesday,15:00-16:00,in_person,60,1
94,74,1,Tuesday,16:00-17:00,online,60,1

In [ ]:
file_path = DATA_RAW / "weekly_slots.csv"

df_weekly_slots.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zapisano:", file_path)

Zapisano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\weekly_slots.csv

In [ ]:
df_calendar_working = df_calendar[
    (df_calendar["weekday"].isin(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"])) &
    (df_calendar["is_holiday"] == 0)
].copy()

df_calendar_working.head()

,date,year,month,month_name,weekday,is_weekend,is_holiday,is_working_day,is_peak_month
0,2025-09-01,2025,9,September,Monday,0,0,1,0
1,2025-09-02,2025,9,September,Tuesday,0,0,1,0
2,2025-09-03,2025,9,September,Wednesday,0,0,1,0
3,2025-09-04,2025,9,September,Thursday,0,0,1,0
4,2025-09-05,2025,9,September,Friday,0,0,1,0

In [ ]:
lesson_rows = []

for _, slot in df_weekly_slots.iterrows():
    student_id = slot["student_id"]
    tutor_id = slot["assigned_tutor_id"]
    weekday = slot["weekday"]
    time_block = slot["time_block"]
    assigned_mode = slot["assigned_mode"]
    duration = slot["typical_duration_minutes"]

    matching_dates = df_calendar_working[df_calendar_working["weekday"] == weekday]

    for _, cal_row in matching_dates.iterrows():
        lesson_rows.append({
            "lesson_date": cal_row["date"],
            "year": cal_row["year"],
            "month": cal_row["month"],
            "month_name": cal_row["month_name"],
            "weekday": weekday,
            "time_block": time_block,
            "student_id": student_id,
            "tutor_id": tutor_id,
            "mode": assigned_mode,
            "duration_minutes": duration
        })

df_lessons = pd.DataFrame(lesson_rows)
df_lessons.head()

,lesson_date,year,month,month_name,weekday,time_block,student_id,tutor_id,mode,duration_minutes
0,2025-09-01,2025,9,September,Monday,17:00-18:00,1,1,in_person,45
1,2025-09-08,2025,9,September,Monday,17:00-18:00,1,1,in_person,45
2,2025-09-15,2025,9,September,Monday,17:00-18:00,1,1,in_person,45
3,2025-09-22,2025,9,September,Monday,17:00-18:00,1,1,in_person,45
4,2025-09-29,2025,9,September,Monday,17:00-18:00,1,1,in_person,45

In [ ]:
df_lessons = df_lessons.sort_values(["lesson_date", "time_block", "tutor_id", "student_id"]).reset_index(drop=True)
df_lessons["lesson_id"] = range(1, len(df_lessons) + 1)

df_lessons.head()

,lesson_date,year,month,month_name,weekday,time_block,student_id,tutor_id,mode,duration_minutes,lesson_id
0,2025-09-01,2025,9,September,Monday,15:00-16:00,59,4,in_person,45,1
1,2025-09-01,2025,9,September,Monday,16:00-17:00,40,1,online,45,2
2,2025-09-01,2025,9,September,Monday,16:00-17:00,45,1,online,90,3
3,2025-09-01,2025,9,September,Monday,16:00-17:00,116,1,in_person,90,4
4,2025-09-01,2025,9,September,Monday,16:00-17:00,122,1,in_person,60,5

In [ ]:
student_columns = [
    "student_id",
    "student_name",
    "age_group",
    "cefr_level",
    "learning_goal",
    "assigned_tutor_id",
    "assigned_tutor_name",
    "prep_profile",
    "sibling_group_id"
]

df_lessons = df_lessons.merge(
    df_students[student_columns],
    on="student_id",
    how="left"
)

df_lessons.head()

,lesson_date,year,month,month_name,weekday,time_block,student_id,tutor_id,mode,duration_minutes,lesson_id,student_name,age_group,cefr_level,learning_goal,assigned_tutor_id,assigned_tutor_name,prep_profile,sibling_group_id
0,2025-09-01,2025,9,September,Monday,15:00-16:00,59,4,in_person,45,1,pan Gustaw Panasiewicz,child,A1,school,4,pani Bianka Kolanko,high,7
1,2025-09-01,2025,9,September,Monday,16:00-17:00,40,1,online,45,2,Fabian Zacharczuk,child,A2,school,1,Marcin Szymków,medium,<NA>
2,2025-09-01,2025,9,September,Monday,16:00-17:00,45,1,online,90,3,Roksana Mordal,pre_teen,B1,school,1,Marcin Szymków,medium,<NA>
3,2025-09-01,2025,9,September,Monday,16:00-17:00,116,1,in_person,90,4,pani Olga Krzykała,pre_teen,B1,school,1,Marcin Szymków,medium,<NA>
4,2025-09-01,2025,9,September,Monday,16:00-17:00,122,1,in_person,60,5,Alex Czylok,teen,A2,school,1,Marcin Szymków,low,<NA>

In [ ]:
tutor_columns = [
    "tutor_id",
    "tutor_name",
    "experience_level",
    "hourly_rate",
    "preferred_mode",
    "home_area"
]

df_lessons = df_lessons.merge(
    df_tutors[tutor_columns],
    on="tutor_id",
    how="left"
)

df_lessons.head()

,lesson_date,year,month,month_name,weekday,time_block,student_id,tutor_id,mode,duration_minutes,...,learning_goal,assigned_tutor_id,assigned_tutor_name,prep_profile,sibling_group_id,tutor_name,experience_level,hourly_rate,preferred_mode,home_area
0,2025-09-01,2025,9,September,Monday,15:00-16:00,59,4,in_person,45,...,school,4,pani Bianka Kolanko,high,7,pani Bianka Kolanko,senior,110,in_person,Warsaw
1,2025-09-01,2025,9,September,Monday,16:00-17:00,40,1,online,45,...,school,1,Marcin Szymków,medium,<NA>,Marcin Szymków,senior,120,mixed,Warsaw
2,2025-09-01,2025,9,September,Monday,16:00-17:00,45,1,online,90,...,school,1,Marcin Szymków,medium,<NA>,Marcin Szymków,senior,120,mixed,Warsaw
3,2025-09-01,2025,9,September,Monday,16:00-17:00,116,1,in_person,90,...,school,1,Marcin Szymków,medium,<NA>,Marcin Szymków,senior,120,mixed,Warsaw
4,2025-09-01,2025,9,September,Monday,16:00-17:00,122,1,in_person,60,...,school,1,Marcin Szymków,low,<NA>,Marcin Szymków,senior,120,mixed,Warsaw

In [ ]:
statuses = []

for _, row in df_lessons.iterrows():
    month = row["month"]

    # wyższe ryzyko anulowania zimą
    if month in [12, 1, 2]:
        status = random.choices(
            ["completed", "cancelled_by_student", "cancelled_by_tutor", "no_show"],
            weights=[84, 10, 2, 4]
        )[0]
    else:
        status = random.choices(
            ["completed", "cancelled_by_student", "cancelled_by_tutor", "no_show"],
            weights=[88, 7, 2, 3]
        )[0]

    statuses.append(status)

df_lessons["status"] = statuses

df_lessons["status"].value_counts()

status
completed               5726
cancelled_by_student     510
no_show                  218
cancelled_by_tutor       111
Name: count, dtype: int64

In [ ]:
prep_times = []

for _, row in df_lessons.iterrows():
    prep_profile = row["prep_profile"]

    if prep_profile == "low":
        prep_time = random.choice([5, 10])
    elif prep_profile == "medium":
        prep_time = random.choice([10, 15])
    else:
        prep_time = random.choice([15, 20])

    prep_times.append(prep_time)

df_lessons["prep_time_minutes"] = prep_times

df_lessons["prep_time_minutes"].value_counts().sort_index()

prep_time_minutes
5      801
10    2375
15    2435
20     954
Name: count, dtype: int64

In [ ]:
travel_times = []

for _, row in df_lessons.iterrows():
    if row["mode"] == "in_person":
        travel_time = random.choice([10, 15, 20, 25, 30, 35, 40])
    else:
        travel_time = 0

    travel_times.append(travel_time)

df_lessons["travel_time_minutes"] = travel_times

df_lessons["travel_time_minutes"].value_counts().sort_index()

travel_time_minutes
0     2080
10     681
15     629
20     629
25     617
30     646
35     622
40     661
Name: count, dtype: int64

In [ ]:
platforms = []

for _, row in df_lessons.iterrows():
    if row["mode"] == "online":
        platform = random.choices(["Teams", "Skype", "Zoom"], weights=[50, 35, 15])[0]
    else:
        platform = "in_person"

    platforms.append(platform)

df_lessons["platform"] = platforms

df_lessons["platform"].value_counts()

platform
in_person    4485
Teams        1019
Skype         720
Zoom          341
Name: count, dtype: int64

In [ ]:
df_lessons["base_price"] = (df_lessons["hourly_rate"] * df_lessons["duration_minutes"] / 60).round(2)

df_lessons[["hourly_rate", "duration_minutes", "base_price"]].head()

   hourly_rate  duration_minutes  base_price
0          110                45        82.5
1          120                45        90.0
2          120                90       180.0
3          120                90       180.0
4          120                60       120.0

In [ ]:
discount_types = []
final_prices = []

for _, row in df_lessons.iterrows():
    base_price = row["base_price"]
    sibling_group_id = row["sibling_group_id"]
    duration = row["duration_minutes"]

    discount_type = "none"
    discount = 0.0

    if pd.notna(sibling_group_id):
        discount_type = "sibling_discount"
        discount = 0.10

    if duration >= 90:
        if discount_type == "none":
            discount_type = "long_lesson_discount"
            discount = 0.08
        else:
            discount_type = "sibling_and_long_lesson"
            discount = 0.15

    final_price = round(base_price * (1 - discount), 2)

    discount_types.append(discount_type)
    final_prices.append(final_price)

df_lessons["discount_type"] = discount_types
df_lessons["final_price"] = final_prices

df_lessons[["base_price", "discount_type", "final_price"]].head(10)

   base_price         discount_type  final_price
0        82.5      sibling_discount        74.25
1        90.0                  none        90.00
2       180.0  long_lesson_discount       165.60
3       180.0  long_lesson_discount       165.60
4       120.0                  none       120.00
5       100.0                  none       100.00
6       100.0      sibling_discount        90.00
7        82.5                  none        82.50
8        82.5                  none        82.50
9       110.0                  none       110.00

In [ ]:
df_lessons.head(20)

,lesson_date,year,month,month_name,weekday,time_block,student_id,tutor_id,mode,duration_minutes,...,hourly_rate,preferred_mode,home_area,status,prep_time_minutes,travel_time_minutes,platform,base_price,discount_type,final_price
0,2025-09-01,2025,9,September,Monday,15:00-16:00,59,4,in_person,45,...,110,in_person,Warsaw,completed,15,30,in_person,82.5,sibling_discount,74.25
1,2025-09-01,2025,9,September,Monday,16:00-17:00,40,1,online,45,...,120,mixed,Warsaw,completed,10,0,Teams,90.0,none,90.00
2,2025-09-01,2025,9,September,Monday,16:00-17:00,45,1,online,90,...,120,mixed,Warsaw,completed,10,0,Teams,180.0,long_lesson_discount,165.60
3,2025-09-01,2025,9,September,Monday,16:00-17:00,116,1,in_person,90,...,120,mixed,Warsaw,completed,10,25,in_person,180.0,long_lesson_discount,165.60
4,2025-09-01,2025,9,September,Monday,16:00-17:00,122,1,in_person,60,...,120,mixed,Warsaw,completed,5,20,in_person,120.0,none,120.00
5,2025-09-01,2025,9,September,Monday,16:00-17:00,53,2,in_person,60,...,100,mixed,Warsaw,completed,15,15,in_person,100.0,none,100.00
6,2025-09-01,2025,9,September,Monday,16:00-17:00,120,2,in_person,60,...,100,mixed,Warsaw,completed,15,25,in_person,100.0,sibling_discount,90.00
7,2025-09-01,2025,9,September,Monday,16:00-17:00,16,4,in_person,45,...,110,in_person,Warsaw,completed,15,20,in_person,82.5,none,82.50
8,2025-09-01,2025,9,September,Monday,16:00-17:00,81,4,in_person,45,...,110,in_person,Warsaw,completed,10,10,in_person,82.5,none,82.50
9,2025-09-01,2025,9,September,Monday,16:00-17:00,85,4,in_person,60,...,110,in_person,Warsaw,cancelled_by_tutor,10,25,in_person,110.0,none,110.00
10,2025-09-01,2025,9,September,Monday,16:00-17:00,102,4,in_person,60,...,110,in_person,Warsaw,completed,10,20,in_person,110.0,none,110.00
11,2025-09-01,2025,9,September,Monday,17:00-18:00,1,1,in_person,45,...,120,mixed,Warsaw,completed,15,30,in_person,90.0,none,90.00
12,2025-09-01,2025,9,September,Monday,17:00-18:00,98,1,in_person,45,...,120,mixed,Warsaw,completed,20,30,in_person,90.0,none,90.00
13,2025-09-01,2025,9,September,Monday,17:00-18:00,100,2,in_person,60,...,100,mixed,Warsaw,completed,15,40,in_person,100.0,none,100.00
14,2025-09-01,2025,9,September,Monday,17:00-18:00,115,4,in_person,45,...,110,in_person,Warsaw,completed,10,25,in_person,82.5,none,82.50
15,2025-09-01,2025,9,September,Monday,18:00-19:00,34,1,in_person,60,...,120,mixed,Warsaw,completed,10,25,in_person,120.0,none,120.00
16,2025-09-01,2025,9,September,Monday,18:00-19:00,37,1,in_person,60,...,120,mixed,Warsaw,completed,5,20,in_person,120.0,none,120.00
17,2025-09-01,2025,9,September,Monday,18:00-19:00,39,1,in_person,90,...,120,mixed,Warsaw,completed,15,15,in_person,180.0,long_lesson_discount,165.60
18,2025-09-01,2025,9,September,Monday,18:00-19:00,40,1,online,45,...,120,mixed,Warsaw,completed,15,0,Teams,90.0,none,90.00
19,2025-09-01,2025,9,September,Monday,18:00-19:00,52,1,online,60,...,120,mixed,Warsaw,completed,10,0,Skype,120.0,none,120.00

In [ ]:
df_lessons.shape

(6565, 31)

In [ ]:
file_path = DATA_RAW / "lessons.csv"

df_lessons.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zapisano:", file_path)

Zapisano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\lessons.csv

In [ ]:
payment_rows = []

In [ ]:
for _, row in df_lessons.iterrows():
    lesson_id = row["lesson_id"]
    lesson_date = row["lesson_date"]
    status = row["status"]
    amount_due = row["final_price"]

    if status == "completed":
        payment_status = random.choices(
            ["paid", "late", "missing"],
            weights=[88, 9, 3]
        )[0]

        if payment_status == "paid":
            amount_paid = amount_due
        elif payment_status == "late":
            amount_paid = amount_due
        else:
            amount_paid = 0

    elif status == "cancelled_by_student":
        payment_status = random.choices(
            ["paid", "partial", "missing"],
            weights=[20, 35, 45]
        )[0]

        if payment_status == "paid":
            amount_paid = amount_due
        elif payment_status == "partial":
            amount_paid = round(amount_due * 0.5, 2)
        else:
            amount_paid = 0

    elif status == "cancelled_by_tutor":
        payment_status = "waived"
        amount_paid = 0

    else:  # no_show
        payment_status = random.choices(
            ["paid", "partial", "missing"],
            weights=[45, 25, 30]
        )[0]

        if payment_status == "paid":
            amount_paid = amount_due
        elif payment_status == "partial":
            amount_paid = round(amount_due * 0.5, 2)
        else:
            amount_paid = 0

    payment_rows.append({
        "lesson_id": lesson_id,
        "lesson_date": lesson_date,
        "amount_due": amount_due,
        "amount_paid": amount_paid,
        "payment_status": payment_status
    })

df_payments = pd.DataFrame(payment_rows)
df_payments.head()

   lesson_id lesson_date  amount_due  amount_paid payment_status
0          1  2025-09-01       74.25        74.25           paid
1          2  2025-09-01       90.00        90.00           late
2          3  2025-09-01      165.60         0.00        missing
3          4  2025-09-01      165.60       165.60           paid
4          5  2025-09-01      120.00       120.00           paid

In [ ]:
df_payments["payment_id"] = range(1, len(df_payments) + 1)
df_payments.head()

   lesson_id lesson_date  amount_due  amount_paid payment_status  payment_id
0          1  2025-09-01       74.25        74.25           paid           1
1          2  2025-09-01       90.00        90.00           late           2
2          3  2025-09-01      165.60         0.00        missing           3
3          4  2025-09-01      165.60       165.60           paid           4
4          5  2025-09-01      120.00       120.00           paid           5

In [ ]:
payment_dates = []

for _, row in df_payments.iterrows():
    lesson_date = pd.to_datetime(row["lesson_date"])
    payment_status = row["payment_status"]

    if payment_status == "paid":
        offset_days = random.choice([0, 1, 2, 3])
        payment_date = lesson_date + pd.Timedelta(days=offset_days)

    elif payment_status == "late":
        offset_days = random.choice([5, 7, 10, 14])
        payment_date = lesson_date + pd.Timedelta(days=offset_days)

    elif payment_status == "partial":
        offset_days = random.choice([0, 2, 5, 7])
        payment_date = lesson_date + pd.Timedelta(days=offset_days)

    else:
        payment_date = pd.NaT

    payment_dates.append(payment_date)

df_payments["payment_date"] = payment_dates
df_payments.head()

,lesson_id,lesson_date,amount_due,amount_paid,payment_status,payment_id,payment_date
0,1,2025-09-01,74.25,74.25,paid,1,2025-09-01
1,2,2025-09-01,90.00,90.00,late,2,2025-09-11
2,3,2025-09-01,165.60,0.00,missing,3,NaT
3,4,2025-09-01,165.60,165.60,paid,4,2025-09-01
4,5,2025-09-01,120.00,120.00,paid,5,2025-09-04

In [ ]:
df_payments = df_payments[
    [
        "payment_id",
        "lesson_id",
        "lesson_date",
        "amount_due",
        "amount_paid",
        "payment_status",
        "payment_date"
    ]
]

df_payments.head()

,payment_id,lesson_id,lesson_date,amount_due,amount_paid,payment_status,payment_date
0,1,1,2025-09-01,74.25,74.25,paid,2025-09-01
1,2,2,2025-09-01,90.00,90.00,late,2025-09-11
2,3,3,2025-09-01,165.60,0.00,missing,NaT
3,4,4,2025-09-01,165.60,165.60,paid,2025-09-01
4,5,5,2025-09-01,120.00,120.00,paid,2025-09-04

In [ ]:
print(df_payments["payment_status"].value_counts())
print()
print(df_payments[["amount_due", "amount_paid"]].describe())

payment_status
paid       5189
late        562
missing     464
partial     239
waived      111
Name: count, dtype: int64

        amount_due  amount_paid
count  6565.000000  6565.000000
mean    107.694912    96.180029
std      23.778927    38.518284
min      63.000000     0.000000
25%      90.000000    82.500000
50%     100.000000   100.000000
75%     120.000000   120.000000
max     165.600000   165.600000

In [ ]:
file_path = DATA_RAW / "payments.csv"

df_payments.to_csv(file_path, index=False, encoding="utf-8-sig")

print("Zapisano:", file_path)

Zapisano: C:\Users\Dell\Desktop\Projekty\tutoring-business-project\data_raw\payments.csv

In [ ]:
print("tutors:", df_tutors.shape)
print("students:", df_students.shape)
print("tutor_availability:", df_tutor_availability.shape)
print("student_availability:", df_student_availability.shape)
print("calendar:", df_calendar.shape)
print("weekly_slots:", df_weekly_slots.shape)
print("lessons:", df_lessons.shape)
print("payments:", df_payments.shape)

tutors: (5, 7)
students: (125, 15)
tutor_availability: (390, 5)
student_availability: (9750, 5)
calendar: (303, 9)
weekly_slots: (158, 7)
lessons: (6565, 31)
payments: (6565, 7)

In [ ]:
def missing_summary(df, df_name):
    missing = df.isna().sum()
    missing = missing[missing > 0]

    print(f"\nMissing values in {df_name}:")
    if len(missing) == 0:
        print("No missing values")
    else:
        print(missing.sort_values(ascending=False))

missing_summary(df_tutors, "df_tutors")
missing_summary(df_students, "df_students")
missing_summary(df_tutor_availability, "df_tutor_availability")
missing_summary(df_student_availability, "df_student_availability")
missing_summary(df_calendar, "df_calendar")
missing_summary(df_weekly_slots, "df_weekly_slots")
missing_summary(df_lessons, "df_lessons")
missing_summary(df_payments, "df_payments")

Missing values in df_tutors:
No missing values

Missing values in df_students:
sibling_group_id    100
dtype: int64

Missing values in df_tutor_availability:
No missing values

Missing values in df_student_availability:
No missing values

Missing values in df_calendar:
No missing values

Missing values in df_weekly_slots:
No missing values

Missing values in df_lessons:
sibling_group_id    5274
dtype: int64

Missing values in df_payments:
payment_date    575
dtype: int64

In [ ]:
print("Unique tutors in students assignment:", df_students["assigned_tutor_id"].nunique())
print("Unique tutors in lessons:", df_lessons["tutor_id"].nunique())
print("Unique students in lessons:", df_lessons["student_id"].nunique())
print("Payment rows vs lesson rows:", len(df_payments), len(df_lessons))

Unique tutors in students assignment: 5
Unique tutors in lessons: 5
Unique students in lessons: 125
Payment rows vs lesson rows: 6565 6565

In [ ]:
print("Lesson statuses:")
print(df_lessons["status"].value_counts())
print()

print("Lesson modes:")
print(df_lessons["mode"].value_counts())
print()

print("Payment statuses:")
print(df_payments["payment_status"].value_counts())
print()

print("Average final lesson price:")
print(round(df_lessons["final_price"].mean(), 2))

Lesson statuses:
status
completed               5726
cancelled_by_student     510
no_show                  218
cancelled_by_tutor       111
Name: count, dtype: int64

Lesson modes:
mode
in_person    4485
online       2080
Name: count, dtype: int64

Payment statuses:
payment_status
paid       5189
late        562
missing     464
partial     239
waived      111
Name: count, dtype: int64

Average final lesson price:
107.69

In [ ]:
df_tutors.to_csv(DATA_CLEAN / "tutors_clean.csv", index=False, encoding="utf-8-sig")
df_students.to_csv(DATA_CLEAN / "students_clean.csv", index=False, encoding="utf-8-sig")
df_tutor_availability.to_csv(DATA_CLEAN / "tutor_availability_clean.csv", index=False, encoding="utf-8-sig")
df_student_availability.to_csv(DATA_CLEAN / "student_availability_clean.csv", index=False, encoding="utf-8-sig")
df_calendar.to_csv(DATA_CLEAN / "calendar_clean.csv", index=False, encoding="utf-8-sig")
df_weekly_slots.to_csv(DATA_CLEAN / "weekly_slots_clean.csv", index=False, encoding="utf-8-sig")
df_lessons.to_csv(DATA_CLEAN / "lessons_clean.csv", index=False, encoding="utf-8-sig")
df_payments.to_csv(DATA_CLEAN / "payments_clean.csv", index=False, encoding="utf-8-sig")

print("Wszystkie clean files zapisane do data_clean")

Wszystkie clean files zapisane do data_clean

In [ ]:
data_dictionary = pd.DataFrame({
    "table_name": [
        "tutors", "students", "tutor_availability", "student_availability",
        "calendar", "weekly_slots", "lessons", "payments"
    ],
    "description": [
        "Tutor master data",
        "Student master data with learning profile",
        "Tutor weekly availability by day and time block",
        "Student weekly availability by day and time block",
        "Calendar table with holidays and working-day flags",
        "Assigned recurring weekly lesson slots",
        "Detailed lesson-level fact table",
        "Payment-level table linked to lessons"
    ]
})

data_dictionary

             table_name                                        description
0                tutors                                  Tutor master data
1              students          Student master data with learning profile
2    tutor_availability    Tutor weekly availability by day and time block
3  student_availability  Student weekly availability by day and time block
4              calendar  Calendar table with holidays and working-day f...
5          weekly_slots             Assigned recurring weekly lesson slots
6               lessons                   Detailed lesson-level fact table
7              payments              Payment-level table linked to lessons

In [ ]:
data_dictionary.to_csv(DATA_CLEAN / "data_dictionary.csv", index=False, encoding="utf-8-sig")
print("Data dictionary zapisany")

Data dictionary zapisany

In [ ]:
expected_revenue = df_lessons["final_price"].sum()
actual_revenue = df_payments["amount_paid"].sum()
revenue_leakage = expected_revenue - actual_revenue

print("Expected revenue:", round(expected_revenue, 2))
print("Actual revenue:", round(actual_revenue, 2))
print("Revenue leakage:", round(revenue_leakage, 2))

Expected revenue: 707017.1
Actual revenue: 631421.89
Revenue leakage: 75595.21

In [ ]:
print("Total lessons:", len(df_lessons))
print()
print("Lesson status breakdown:")
print(df_lessons["status"].value_counts())
print()
print("Mode breakdown:")
print(df_lessons["mode"].value_counts())

Total lessons: 6565

Lesson status breakdown:
status
completed               5726
cancelled_by_student     510
no_show                  218
cancelled_by_tutor       111
Name: count, dtype: int64

Mode breakdown:
mode
in_person    4485
online       2080
Name: count, dtype: int64

In [ ]:
cancelled_lessons = df_lessons["status"].isin(["cancelled_by_student", "cancelled_by_tutor", "no_show"]).sum()
total_lessons = len(df_lessons)
cancellation_rate = cancelled_lessons / total_lessons

print("Cancelled / not completed lessons:", cancelled_lessons)
print("Cancellation / disruption rate:", round(cancellation_rate * 100, 2), "%")

Cancelled / not completed lessons: 839
Cancellation / disruption rate: 12.78 %

In [ ]:
tutor_workload = df_lessons.groupby(["tutor_id", "tutor_name"]).agg(
    total_lessons=("lesson_id", "count"),
    total_teaching_minutes=("duration_minutes", "sum"),
    avg_price=("final_price", "mean")
).reset_index()

tutor_workload["total_teaching_hours"] = (tutor_workload["total_teaching_minutes"] / 60).round(2)

tutor_workload.sort_values("total_lessons", ascending=False)

,tutor_id,tutor_name,total_lessons,total_teaching_minutes,avg_price,total_teaching_hours
0,1,Marcin Szymków,2861,177300,119.249004,2955.00
1,2,pani Agnieszka Słomiany,2115,131895,100.151064,2198.25
3,4,pani Bianka Kolanko,1005,58425,102.856020,973.75
2,3,Elżbieta Borysiuk,329,20970,97.131003,349.50
4,5,pani Aurelia Malcherek,255,16590,73.332549,276.50

In [ ]:
tutor_revenue = df_lessons.groupby(["tutor_id", "tutor_name"]).agg(
    expected_revenue=("final_price", "sum")
).reset_index()

actual_by_tutor = df_lessons.merge(
    df_payments[["lesson_id", "amount_paid"]],
    on="lesson_id",
    how="left"
).groupby(["tutor_id", "tutor_name"]).agg(
    actual_revenue=("amount_paid", "sum")
).reset_index()

tutor_revenue_summary = tutor_revenue.merge(actual_by_tutor, on=["tutor_id", "tutor_name"])
tutor_revenue_summary["revenue_gap"] = (
    tutor_revenue_summary["expected_revenue"] - tutor_revenue_summary["actual_revenue"]
).round(2)

tutor_revenue_summary.sort_values("expected_revenue", ascending=False)

,tutor_id,tutor_name,expected_revenue,actual_revenue,revenue_gap
0,1,Marcin Szymków,341171.4,305129.40,36042.00
1,2,pani Agnieszka Słomiany,211819.5,187867.25,23952.25
3,4,pani Bianka Kolanko,103370.3,92182.74,11187.56
2,3,Elżbieta Borysiuk,31956.1,29408.20,2547.90
4,5,pani Aurelia Malcherek,18699.8,16834.30,1865.50

In [ ]:
age_group_summary = df_lessons.groupby("age_group").agg(
    total_lessons=("lesson_id", "count"),
    avg_price=("final_price", "mean"),
    total_revenue=("final_price", "sum")
).reset_index()

age_group_summary.sort_values("total_revenue", ascending=False)

   age_group  total_lessons   avg_price  total_revenue
4       teen           2072  114.449373       237139.1
3   pre_teen           1409  104.200284       146818.2
1      child           1503   93.981371       141254.0
2  exam_prep            825  125.126061       103229.0
0      adult            756  103.937566        78576.8

In [ ]:
mode_summary = df_lessons.groupby("mode").agg(
    total_lessons=("lesson_id", "count"),
    avg_price=("final_price", "mean"),
    total_revenue=("final_price", "sum"),
    avg_travel_time=("travel_time_minutes", "mean")
).reset_index()

mode_summary

        mode  total_lessons   avg_price  total_revenue  avg_travel_time
0  in_person           4485  108.765753       487814.4        24.936455
1     online           2080  105.385913       219202.7         0.000000

In [ ]:
payment_summary = df_payments.groupby("payment_status").agg(
    count=("payment_id", "count"),
    total_due=("amount_due", "sum"),
    total_paid=("amount_paid", "sum")
).reset_index()

payment_summary

  payment_status  count  total_due  total_paid
0           late    562   60920.95    60920.95
1        missing    464   50224.55        0.00
2           paid   5189  557358.35   557358.35
3        partial    239   26285.20    13142.59
4         waived    111   12228.05        0.00

In [ ]:
monthly_summary = df_lessons.groupby(["year", "month", "month_name"]).agg(
    total_lessons=("lesson_id", "count"),
    expected_revenue=("final_price", "sum")
).reset_index()

monthly_actual = df_lessons.merge(
    df_payments[["lesson_id", "amount_paid"]],
    on="lesson_id",
    how="left"
).groupby(["year", "month", "month_name"]).agg(
    actual_revenue=("amount_paid", "sum")
).reset_index()

monthly_summary = monthly_summary.merge(
    monthly_actual,
    on=["year", "month", "month_name"],
    how="left"
)

monthly_summary["revenue_gap"] = (
    monthly_summary["expected_revenue"] - monthly_summary["actual_revenue"]
).round(2)

monthly_summary.sort_values(["year", "month"])

,year,month,month_name,total_lessons,expected_revenue,actual_revenue,revenue_gap
0,2025,9,September,687,73915.65,66463.67,7451.98
1,2025,10,October,722,77776.35,69181.20,8595.15
2,2025,11,November,606,65293.00,57935.25,7357.75
3,2025,12,December,625,67173.20,58795.60,8377.60
4,2026,1,January,643,69371.85,61648.77,7723.08
5,2026,2,February,632,68083.60,60274.10,7809.50
6,2026,3,March,687,73915.65,66579.35,7336.30
7,2026,4,April,669,72152.15,65488.70,6663.45
8,2026,5,May,645,69579.70,63020.65,6559.05
9,2026,6,June,649,69755.95,62034.60,7721.35

In [ ]:
tutor_workload.to_csv(DATA_CLEAN / "summary_tutor_workload.csv", index=False, encoding="utf-8-sig")
tutor_revenue_summary.to_csv(DATA_CLEAN / "summary_tutor_revenue.csv", index=False, encoding="utf-8-sig")
age_group_summary.to_csv(DATA_CLEAN / "summary_age_group.csv", index=False, encoding="utf-8-sig")
mode_summary.to_csv(DATA_CLEAN / "summary_mode.csv", index=False, encoding="utf-8-sig")
payment_summary.to_csv(DATA_CLEAN / "summary_payment.csv", index=False, encoding="utf-8-sig")
monthly_summary.to_csv(DATA_CLEAN / "summary_monthly.csv", index=False, encoding="utf-8-sig")

print("Summary files saved.")

Summary files saved.